Initialize CVS branch cherry-xenmp
The per-file CVS branch roots do not exactly match a reconstructed source-branch commit.

diff --git a/etc/rc.d/fsck b/etc/rc.d/fsck
--- a/etc/rc.d/fsck
+++ b/etc/rc.d/fsck
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: fsck,v 1.7 2007/04/06 14:20:17 apb Exp $
+# $NetBSD: fsck,v 1.11 2010/02/17 23:32:07 christos Exp $
 #
 
 # PROVIDE: fsck
@@ -16,41 +16,14 @@ fsck_start()
 {
 	if [ -e /fastboot ]; then
 		echo "Fast boot: skipping disk checks."
-	else
-		trap : 2		# Ignore SIGINT, SIGQUIT, so we
-		trap : 3		# enter single-user mode on failure.
-
-		echo "Starting file system checks:"
-		fsck $fsck_flags
-		case $? in
-		0)
-			;;
-		2)
-			stop_boot
-			;;
-		4)
-			echo "Rebooting..."
-			reboot
-			echo "Reboot failed; help!"
-			stop_boot
-			;;
-		8)
-			echo "Automatic file system check failed; help!"
-			stop_boot
-			;;
-		12)
-			echo "Boot interrupted."
-			stop_boot
-			;;
-		130)
-			stop_boot
-			;;
-		*)
-			echo "Unknown error; help!"
-			stop_boot
-			;;
-		esac
+		return
 	fi
+	trap : 2 		# Ignore SIGINT, SIGQUIT, so we
+	trap : 3		# enter single-user mode on failure.
+
+	echo "Starting file system checks:"
+	fsck -x / $fsck_flags
+	handle_fsck_error "$?"
 }
 
 load_rc_config $name
