Initialize CVS branch netbsd-3-0
The per-file CVS branch roots do not exactly match a reconstructed source-branch commit.

diff --git a/etc/rc.d/pf b/etc/rc.d/pf
--- a/etc/rc.d/pf
+++ b/etc/rc.d/pf
@@ -1,30 +1,53 @@
 #!/bin/sh
 #
-# $NetBSD: pf,v 1.3 2005/03/15 18:22:03 peter Exp $
+# $NetBSD: pf,v 1.3.2.3 2005/09/02 12:29:37 tron Exp $
 #
 
 # PROVIDE: pf
-# REQUIRE: NETWORKING
-# BEFORE: SERVERS
+# REQUIRE: root beforenetlkm mountcritlocal tty network dhclient
+# BEFORE: NETWORKING
 
 $_rc_subr_loaded . /etc/rc.subr
 
 name="pf"
 rcvar=$name
+start_precmd="pf_prestart"
 start_cmd="pf_start"
 stop_cmd="pf_stop"
 reload_cmd="pf_reload"
 status_cmd="pf_status"
 extra_commands="reload status"
 
+pf_prestart()
+{
+	if [ ! -f ${pf_rules} ]; then
+		warn "${pf_rules} not readable; pf start aborted."
+
+		# If booting directly to multiuser, send SIGTERM to
+		# the parent (/etc/rc) to abort the boot
+		if [ "$autoboot" = yes ]; then
+			echo "ERROR: ABORTING BOOT (sending SIGTERM to parent)!"
+			kill -TERM $$
+			exit 1
+		fi
+		return 1
+	fi
+	return 0
+}
+
 pf_start()
 {
 	echo "Enabling pf firewall."
-	/sbin/pfctl -q -e 
-	if [ -f /etc/pf.conf ]; then
-		/sbin/pfctl -q -f /etc/pf.conf
+
+	# The pf_boot script has enabled pf already.
+	if [ "$autoboot" != yes ]; then
+		/sbin/pfctl -q -e 
+	fi
+
+	if [ -f ${pf_rules} ]; then
+		/sbin/pfctl -q -f ${pf_rules}
 	else
-		warn "pf.conf not found; no pf rules loaded."
+		warn "${pf_rules} not found; no pf rules loaded."
 	fi
 }
 
@@ -37,10 +60,10 @@ pf_stop()
 pf_reload()
 {
 	echo "Reloading pf rules."
-	if [ -f /etc/pf.conf ]; then
-		/sbin/pfctl -q -f /etc/pf.conf
+	if [ -f ${pf_rules} ]; then
+		/sbin/pfctl -q -f ${pf_rules}
 	else
-		warn "pf.conf not found; no pf rules loaded."
+		warn "${pf_rules} not found; no pf rules loaded."
 	fi
 }
 
