Initialize CVS branch matt-nb5-mips64
The per-file CVS branch roots do not exactly match a reconstructed source-branch commit.

diff --git a/distrib/sets/checkflist b/distrib/sets/checkflist
--- a/distrib/sets/checkflist
+++ b/distrib/sets/checkflist
@@ -1,64 +1,198 @@
 #! /bin/sh --
 #
-#	$NetBSD: checkflist,v 1.12 2000/01/06 21:03:34 abs Exp $
+#	$NetBSD: checkflist,v 1.33 2006/09/11 22:16:10 dbj Exp $
 #
-# Verify output of makeflist against contents of $DESTDIR.
+# Verify output of makeflist against contents of ${DESTDIR} and ${metalog}.
 
-[ "$DESTDIR" ] || {
-	echo DESTDIR must be set
+if [ -z "${DESTDIR}" ]; then
+	echo "DESTDIR must be set"
 	exit 1
+fi
+
+prog="${0##*/}"
+rundir="$(dirname "$0")" # ${0%/*} isn't good enough when there's no "/"
+. "${rundir}/sets.subr"
+
+SDIR="$(${MKTEMP} -d "/tmp/${prog}.XXXXXX")"
+
+es=0
+cleanup()
+{
+	/bin/rm -rf "${SDIR}"
+	if [ ${es} -gt 255 ]; then
+		es=255
+	fi
+	exit ${es}
 }
+trap cleanup 0 2 3 13		# EXIT INT QUIT PIPE
 
 origin=.
-tmpname=/tmp/_CHECK.$$
-
 xargs=""
 dargs=""
-diffargs=""
+metalog=
+allowextra=false
+allowmissing=false
 
 # handle args
-while : ; do
-	case $1 in
-	-x11)
+while getopts xbM:em ch; do
+	case ${ch} in
+	x)
 		xargs="-x"
-		origin=./usr/X11R6
+		origin="./etc/X11 ./etc/fonts ./usr/X11R6"
 		;;
-	-both)
+	b)
 		xargs="-b"
 		;;
-	-secr)
-		dargs="-d"
+	M)
+		metalog="${OPTARG}"
 		;;
-	-cryptint)
-		dargs="-i"
+	e)
+		allowextra=true
 		;;
-	-u)
-		diffargs="-u"
+	m)
+		allowmissing=true
 		;;
-	-c)
-		diffargs="-c"
-		;;
-	-*)
+	*)
 		cat 1>&2 <<USAGE
-Usage: $0 [-x11|-both] [-secr]
-	-x11		check only x11 lists
-	-both		check netbsd + x11 lists
-	-secr		check domestic ("secr") lists
-	-cryptint	check international crypto ("cryptint") lists
-	-u		output differences in "unified diff" style
-	-c		output differences in "context diff" style
+Usage: ${prog} [-x|-b] [-M metalog] [-e] [-m]
+	-x		check only x11 lists
+	-b		check netbsd + x11 lists
+	-M metalog	metalog file
+	-e		extra files are not considered an error
+	-m		missing files are not considered an error
 USAGE
 		exit 1
 		;;
-	*)
-		break
-		;;
 	esac
-	shift
 done
+shift $((${OPTIND} - 1))
 
-sh makeflist $xargs $dargs > $tmpname
+#
+# Exceptions to flist checking (all begin with "./"):
+#
+# * ignore var/db/syspkg and its contents
+# * ignore ${metalog}
+# * ignore METALOG
+# * ignore etc/mtree/set.*
+#
+IGNORE_REGEXP="^\./var/db/syspkg(\$|/)"
+if [ -n "${metalog}" ]; then
+	ml="${metalog#${DESTDIR}/}"
+	ml2="METALOG"
+	IGNORE_REGEXP="${IGNORE_REGEXP}|^\./${ml}\$|^\./${ml2}\$"
+	IGNORE_REGEXP="${IGNORE_REGEXP}|^\./etc/mtree/set\.[a-z]*\$"
+fi
 
-( cd $DESTDIR ; find $origin \( -type d -o -type f -o -type l \) ) | sort | \
-    diff $diffargs $tmpname -
-/bin/rm -f $tmpname
+#
+# Here would be a good place to add custom exceptions to flist checking.
+#
+
+#
+# Make three lists:
+# * ${SDIR}/files: files present in DESTDIR.
+# * ${SDIR}/flist: files mentioned in flist;
+# * ${SDIR}/mlist: files mentioned in metalog;
+#
+( cd "${DESTDIR}" && ${FIND} ${origin} \
+	\( -type d -o -type f -o -type l \) -print ) \
+	| ${SORT} -u | ${EGREP} -v -e "${IGNORE_REGEXP}" >"${SDIR}/files"
+${HOST_SH} "${rundir}/makeflist" ${xargs} ${dargs} \
+	| ${SORT} -u | ${EGREP} -v -e "${IGNORE_REGEXP}" >"${SDIR}/flist"
+if [ -n "${metalog}" ]; then
+	${AWK} '{print $1}' <"${metalog}" \
+	| ${SORT} -u | ${EGREP} -v -e "${IGNORE_REGEXP}" >"${SDIR}/mlist"
+fi
+
+#
+# compare DESTDIR with METALOG, and report on differences.
+#
+# XXX: Temporarily disabled due to problems with obsolete files in metalog
+#
+if false && [ -n "${metalog}" ]; then
+    ${COMM} -23 "${SDIR}/files" "${SDIR}/mlist" > "${SDIR}/missing"
+    ${COMM} -13 "${SDIR}/files" "${SDIR}/mlist" > "${SDIR}/extra"
+
+    # Handle case insensitive filesystems
+    mv -f "${SDIR}/extra" "${SDIR}/extra.all"
+    while read f; do
+	[ -f "${DESTDIR}/${f}" ] || \
+	    [ -d "${DESTDIR}/${f}" ] || \
+	    [ -L "${DESTDIR}/${f}" ] || echo "$f"
+    done < "${SDIR}/extra.all" > "${SDIR}/extra"
+
+    if [ -s "${SDIR}/extra" ]; then
+	count="$(${AWK} 'END {print NR}' "${SDIR}/extra")"
+	echo ""
+	echo "=======  ${count} extra files in METALOG  ========="
+	echo "Files in METALOG but missing from DESTDIR."
+	echo "File was deleted after installation ?"
+	echo "------------------------------------------"
+	cat "${SDIR}/extra"
+	echo "=========  end of ${count} extra files  ==========="
+	echo ""
+	es=1 # this is fatal even if ${allowextra} is true
+    fi
+
+    if [ -s "${SDIR}/missing" ]; then
+	count="$(${AWK} 'END {print NR}' "${SDIR}/missing")"
+	echo ""
+	echo "======  ${count} missing files in METALOG  ========"
+	echo "Files in DESTDIR but missing from METALOG."
+	echo "File installed but not registered in METALOG ?"
+	echo "------------------------------------------"
+	cat "${SDIR}/missing"
+	echo "========  end of ${count} missing files  =========="
+	echo ""
+	es=1 # this is fatal even if ${allowmissing} is true
+    fi
+fi
+
+#
+# compare flist with DESTDIR, and report on differences.
+#
+${COMM} -23 "${SDIR}/flist" "${SDIR}/files" > "${SDIR}/missing"
+${COMM} -13 "${SDIR}/flist" "${SDIR}/files" > "${SDIR}/extra"
+
+# Handle case insensitive filesystems
+mv -f "${SDIR}/missing" "${SDIR}/missing.all"
+while read f; do
+    [ -f "${DESTDIR}/${f}" ] || \
+	[ -d "${DESTDIR}/${f}" ] || \
+	[ -L "${DESTDIR}/${f}" ] || echo "$f"
+done < "${SDIR}/missing.all" > "${SDIR}/missing"
+
+if [ -s "${SDIR}/extra" ]; then
+	count="$(${AWK} 'END {print NR}' "${SDIR}/extra")"
+	echo ""
+	echo "=======  ${count} extra files in DESTDIR  ========="
+	echo "Files in DESTDIR but missing from flist."
+	echo "File is obsolete or flist is out of date ?"
+	if ${allowextra}; then
+		echo "This is non-fatal, due to '-e' option."
+	else
+		es=1
+	fi
+	echo "------------------------------------------"
+	cat "${SDIR}/extra"
+	echo "=========  end of ${count} extra files  ==========="
+	echo ""
+fi
+
+if [ -s "${SDIR}/missing" ]; then
+	count="$(${AWK} 'END {print NR}' "${SDIR}/missing")"
+	echo ""
+	echo "======  ${count} missing files in DESTDIR  ========"
+	echo "Files in flist but missing from DESTDIR."
+	echo "File wasn't installed ?"
+	if ${allowmissing}; then
+		echo "This is non-fatal, due to '-m' option."
+	else
+		es=1
+	fi
+	echo "------------------------------------------"
+	cat "${SDIR}/missing"
+	echo "========  end of ${count} missing files  =========="
+	echo ""
+fi
+
+exit 0		# cleanup will exit with ${es}
diff --git a/distrib/sets/makesrctars b/distrib/sets/makesrctars
--- a/distrib/sets/makesrctars
+++ b/distrib/sets/makesrctars
@@ -1,84 +1,143 @@
 #! /bin/sh
 #
-#	$NetBSD: makesrctars,v 1.10 1998/11/07 16:59:13 he Exp $
+#	$NetBSD: makesrctars,v 1.34 2008/03/16 07:02:22 lukem Exp $
 #
-# Make source code tarballs.
+# makesrctars srcdir setdir
+#	Create source tarballs in setdir from the source under srcdir.
+#
 
-GZIP=--best
+prog="${0##*/}"
+rundir="$(dirname "$0")" # ${0%/*} isn't good enough when there's no "/"
+. "${rundir}/sets.subr"
+
+# set defaults
+xsrcdir=
+quiet=false
+
+GZIP=-9
 export GZIP
 
-if [ -z "$SRCDIR" ]; then
-	echo SRCDIR must be set
+usage()
+{
+	cat 1>&2 <<USAGE
+Usage: ${prog} [-N password/group dir] [-q] [-x xsrcdir] srcdir setdir
+	-N dir		location which contains master.passwd and group files
+			(defaults to \${srcdir}/etc)
+	-q		quiet operation
+	-x xsrcdir	build xsrc.tgz from xsrcdir
+	srcdir		location of sources
+	setdir		where to write the .tgz files to
+USAGE
+	exit 1
+}
+
+msg()
+{
+	$quiet || echo $*
+}
+
+
+# handle args
+while getopts N:qx: ch; do
+	case ${ch} in
+	q)
+		quiet=true
+		;;
+	x)
+		xsrcdir="${OPTARG}"
+		;;
+	N)
+		PASSWD="${OPTARG}"
+		;;
+	*)
+		usage
+		;;
+	esac
+done
+shift $((${OPTIND} - 1))
+
+if [ $# -ne 2 ]; then
+	usage
+fi
+srcdir="$1"
+setdir="$2"
+: ${PASSWD:="${srcdir}/etc"}
+
+if [ ! -d "${setdir}" ]; then
+	echo >&2 "${prog}: ${setdir} is not a directory"
 	exit 1
 fi
 
-if [ -z "$DESTDIR" ]; then
-	echo DESTDIR must be set
+makeset()
+{(
+	set="${1}.tgz"
+	shift
+	dir="$1"
+	shift
+	intmp="/tmp/in$$"
+	msg "Creating ${set}"
+	if [ "${dir}" != "." ]; then
+		cd "${dir}"
+		srcprefix="${srcprefix}/${dir}"
+	fi
+	# Gets rid of any obj dirs and things below it 
+	echo "obj" > "${intmp}"
+	egrep="$*"
+	if [ "${egrep}" = "" ]; then
+		egrep='.'
+	fi
+	set -f
+	${MTREE} -c -X "${intmp}" | ${MTREE} -C -k type | \
+		${EGREP} -v 'type=link' | ${EGREP} ${egrep} | \
+		${SED} -e 's:type=file:& mode=0664:' \
+			-e 's:type=dir:& mode=0775:' \
+			-e 's:$: uname=root gname=wsrc:' \
+			-e '/\/move-if-change /s:\(mode\)=[0-9]*:\1=0775:' \
+			-e '/^\.\/build.sh /s:\(mode\)=[0-9]*:\1=0775:' | \
+		${PAX} -M -N "${PASSWD}" -w -d -s'|^\.|'"${srcprefix}"'|' | \
+		${GZIP_CMD} > "${setdir}/${set}"
+	rm -f "${intmp}"
+)}
+
+
+# create (base)src sets
+#
+
+if ! cd "${srcdir}"; then
+	echo >&2 "${prog}: can't chdir to ${srcdir}"
 	exit 1
 fi
 
-if [ -d ${DESTDIR} ]; then
-	echo "DESTDIR exists."
-	exit 1
+srcprefix=usr/src
+export setdir MTREE PAX CKSUM GZIP PASSWD srcprefix
+
+makeset src . -v '^\.\/gnu|^\.\/share|^\.\/sys|^\.\/usr\.bin\/config|^\.\/common'
+
+makeset gnusrc gnu
+
+makeset syssrc . -e '^\..type=dir|^\.\/sys|^\.\/usr\.bin.type=dir|^\.\/usr\.bin\/config|^\.\/common'
+
+makeset sharesrc share
+
+
+# create xsrc sets
+#
+if [ -n "${xsrcdir}" ]; then
+	if ! cd "${xsrcdir}"; then
+		echo >&2 "${prog}: can't chdir to ${xsrcdir}"
+		exit 1
+	fi
+	srcprefix=usr/xsrc
+	makeset xsrc .
 fi
 
-cd $SRCDIR
 
-mkdir ${DESTDIR}
-
-mkdir ${DESTDIR}/sets
-
-find . \
-    \! \( \( -path ./gnu -o -path ./share -o -path ./domestic \) -prune \) \
-    \! \( -path ./sys -prune \) \
-    \! \( -path ./usr.sbin/config -prune \) \
-    \! \( -path ./usr.sbin/dbsym -prune \) \
-    \! \( \( -type l -o -type d \) \( -name obj -o -name 'obj.*' \) \) \
-	-print | \
-	sort | pax -w -d -s'|^\.|usr/src|' | gzip \
-	> ${DESTDIR}/sets/src.tgz
-
-find gnu \
-    \! \( \( -type l -o -type d \) \( -name obj -o -name 'obj.*' \) \) \
-	-print | \
-	sort | pax -w -d -s'|^|usr/src/|' | gzip \
-	> ${DESTDIR}/sets/gnusrc.tgz
-
-find sys usr.sbin/config usr.sbin/dbsym \
-    \( \
-	-path 'sys/arch/*/compile/CVS' -o \
-	-name .keep_me -o \
-	! \( -path 'sys/arch/*/compile/*' -prune \) \
-    \) \
-    ! \( \( -type l -o -type d \) \( -name obj -o -name 'obj.*' \) \) \
-	-print | \
-	sort | pax -w -d -s'|^|usr/src/|' | gzip \
-	> ${DESTDIR}/sets/syssrc.tgz
-
-find share \
-    \! \( \( -type l -o -type d \) \( -name obj -o -name 'obj.*' \) \) \
-	-print | \
-	sort | pax -w -d -s'|^|usr/src/|' | gzip \
-	> ${DESTDIR}/sets/sharesrc.tgz
-
-(cd ${DESTDIR}/sets
- cksum -o1 *.tgz > BSDSUM
- cksum *.tgz > CKSUM
- cksum -o2 *.tgz > SYSVSUM
- md5 *.tgz > MD5)
-chmod 444 ${DESTDIR}/sets/*
-
-mkdir ${DESTDIR}/security
-
-find domestic \
-    \! \( \( -type l -o -type d \) \( -name obj -o -name 'obj.*' \) \) \
-	-print | \
-	sort | pax -w -d -s'|^|usr/src/|' | gzip \
-	> ${DESTDIR}/security/secrsrc.tgz
-
-(cd ${DESTDIR}/security
- cksum -o1 *.tgz > BSDSUM
- cksum *.tgz > CKSUM
- cksum -o2 *.tgz > SYSVSUM
- md5 *.tgz > MD5)
-chmod 444 ${DESTDIR}/security/*
+msg "Creating checksum files"
+(cd "${setdir}"
+	${CKSUM} -o1 *.tgz > BSDSUM
+	${CKSUM}     *.tgz > CKSUM
+	${CKSUM} -a md5  *.tgz > MD5
+	${CKSUM} -o2 *.tgz > SYSVSUM
+	${CKSUM} -a sha512 *.tgz > SHA512
+)
+exit 0
diff --git a/etc/daily b/etc/daily
--- a/etc/daily
+++ b/etc/daily
@@ -1,6 +1,6 @@
 #!/bin/sh -
 #
-#	$NetBSD: daily,v 1.32 2000/01/20 04:13:54 itojun Exp $
+#	$NetBSD: daily,v 1.71 2008/08/30 10:53:22 bouyer Exp $
 #	@(#)daily	8.2 (Berkeley) 1/25/94
 #
 
@@ -13,6 +13,7 @@ fi
 
 host=`hostname`
 date=`date`
+rcvar_manpage='daily.conf(5)'
 
 echo "To: ${MAILTO:-root}"
 echo "Subject: $host daily output for $date"
@@ -47,7 +48,8 @@ echo "Uptime: " `uptime`
 #if [ -d /var/tmp -a ! -h /var/tmp ]; then
 #	cd /var/tmp && {
 #	find . ! -name . -atime +7 -exec rm -f -- {} \;
-#	find . ! -name . -type d -mtime +1 -exec rmdir -- {} \; \
+#	find . ! \( -name . -o -name vi.recover \) -type d \
+#		-mtime +1 -exec rmdir -- {} \; \
 #	    >/dev/null 2>&1; }
 #fi
 
@@ -64,15 +66,12 @@ echo "Uptime: " `uptime`
 #	find . ! -name . -mtime +7 -exec rm -f -- {} \; ; }
 #fi
 
-TMPDIR=/tmp/_daily.$$
+DAILYDIR=$(mktemp -d -t _daily) || exit 1
 
-if ! mkdir $TMPDIR; then
-	echo can not create $TMPDIR.
-	exit 1
-fi
+trap "/bin/rm -rf $DAILYDIR ; exit 0" EXIT INT QUIT
 
-if ! cd $TMPDIR; then
-	echo can not cd to $TMPDIR.
+if ! cd "$DAILYDIR"; then
+	echo "Can not cd to $DAILYDIR".
 	exit 1
 fi
 
@@ -80,10 +79,13 @@ TMP=daily.$$
 TMP2=daily2.$$
 
 if checkyesno find_core; then
-	find / \( ! -fstype local -o -fstype rdonly -o -fstype fdesc \
-		-o -fstype kernfs -o -fstype procfs \) -a -prune -o \
-		-name 'lost+found' -a -prune -o \
-		\( -name '*.core' -o -name 'core' \) -a -print > $TMP
+	# Turn "foo !bar bax" into "-fstype foo -o ! -fstype bar -o -fstype bax"
+	ignfstypes=`echo $find_core_ignore_fstypes | \
+		sed -e's/\(!*\)\([^[:space:]]\{1,\}\)/-o \1 -fstype \2/g' \
+		    -e's/^-o //'`
+	find / \( $ignfstypes \) -prune -o \
+		-name 'lost+found' -prune -o \
+		\( -name '*.core' -o -name 'core' \) -type f -print > $TMP
 #		\( -name '[#,]*' -o -name '.#*' -o -name a.out \
 #		   -o -name '*.CKP' -o -name '.emacs_[0-9]*' \) \
 #			-a -atime +3 -exec rm -f -- {} \; -a -print > $TMP
@@ -116,15 +118,24 @@ fi
 if checkyesno purge_accounting && [ -f /var/account/acct ]; then
 	echo ""
 	echo "Purging accounting records:"
-	mv /var/account/acct.2 /var/account/acct.3
-	mv /var/account/acct.1 /var/account/acct.2
-	mv /var/account/acct.0 /var/account/acct.1
+	if [ -f /var/account/acct.0.gz ]; then
+		mv /var/account/acct.2.gz /var/account/acct.3.gz 2>/dev/null
+		mv /var/account/acct.1.gz /var/account/acct.2.gz 2>/dev/null
+		mv /var/account/acct.0.gz /var/account/acct.1.gz 2>/dev/null
+	else
+		mv /var/account/acct.2 /var/account/acct.3 2>/dev/null
+		mv /var/account/acct.1 /var/account/acct.2 2>/dev/null
+		mv /var/account/acct.0 /var/account/acct.1 2>/dev/null
+	fi
 	cp /var/account/acct /var/account/acct.0
 	sa -sq
+	if [ -f /var/account/acct.1.gz ]; then
+		gzip /var/account/acct.0
+	fi
 fi
 
 if checkyesno run_calendar; then
-	calendar -a > $TMP
+	calendar -a > $TMP 2>&1
 	if [ -s $TMP ]; then
 		echo ""
 		echo "Running calendar:"
@@ -133,23 +144,22 @@ if checkyesno run_calendar; then
 	rm -f $TMP
 fi
 
-if checkyesno check_uucp && \
-    [ -d /var/spool/uucp -a -f /usr/libexec/uucp/clean.daily ]; then
-	echo ""
-	echo "Cleaning up UUCP:"
-	su daemon -c /usr/libexec/uucp/clean.daily
-fi
-
 if checkyesno check_disks; then
-	df -k > $TMP 
-	dump W > $TMP2
+	if checkyesno show_remote_fs; then
+		df -hi -t nokernfs,procfs,null,fdesc > $TMP
+	else
+		df -hil -t nokernfs,procfs,null,fdesc > $TMP
+	fi
+	if [ -s /etc/dumpdates ] ; then
+		dump -W > $TMP2
+	fi
 	if [ -s $TMP -o -s $TMP2 ]; then
 		echo ""
 		echo "Checking subsystem status:"
 		echo ""
 		echo "disks:"
 		if [ -s $TMP ]; then
-			cat $TMP
+			cat $TMP | sed 's/Mounted on/Mount/'
 			echo ""
 		fi
 		if [ -s $TMP2 ]; then
@@ -158,26 +168,28 @@ if checkyesno check_disks; then
 		fi
 		echo ""
 	fi
+	rm -f $TMP $TMP2
+	touch $TMP2
+	for dev in `iostat -x | awk '/^raid/ { print $1 }'`; do
+		raidctl -s $dev | awk '/^.*: failed$/ {print $0}' > $TMP
+		if [ -s $TMP ]; then
+			echo "$dev:" >> $TMP2
+			cat $TMP >> $TMP2
+		fi
+		rm -f $TMP
+	done
+	if [ -s $TMP2 ]; then
+		echo "failed RAIDframe component(s):"
+			cat $TMP2
+	fi
+	rm -f $TMP2
 fi
-
-rm -f $TMP $TMP2
 
 if checkyesno check_mailq; then
 	mailq > $TMP
-	if ! grep -q "^Mail queue is empty$" $TMP; then
+	if ! grep -q "queue is empty$" $TMP; then
 		echo ""
 		echo "mail:"
-		cat $TMP
-	fi
-fi
-
-rm -f $TMP
-
-if checkyesno check_uucp && [ -d /var/spool/uucp ]; then
-	uustat -a > $TMP
-	if [ -s $TMP ]; then
-		echo ""
-		echo "uucp:"
 		cat $TMP
 	fi
 fi
@@ -187,11 +199,25 @@ rm -f $TMP
 if checkyesno check_network; then
 	echo ""
 	echo "network:"
-	# excluding IPv6
-	netstat -in | awk 'NR == 1 {print;} NR > 1 {if ($3 !~ /:/) print; }'
-	echo ""
-	echo "IPv6 network:"
-	netstat -inv | awk 'NR == 1 {print;} NR > 1 {if ($3 ~ /:/) print; }'
+	if checkyesno full_netstat; then
+		netstat -inv
+	else
+		netstat -inv | awk 'BEGIN {
+			ifs[""] = 0;
+		}
+		/^[^\*]* / {
+			if (NR == 1) {
+				printf("%-8s %12s %6s %12s %6s %6s\n",
+				  $1, $(NF-4), $(NF-3), $(NF-2), $(NF-1), $NF);
+				next;
+			}
+			if (!($1 in ifs)) {
+				printf("%-8s %12s %6s %12s %6s %6s\n",
+				  $1, $(NF-4), $(NF-3), $(NF-2), $(NF-1), $NF);
+				ifs[$1] = 1;
+			}
+		}'
+	fi
 	echo ""
 	t=/var/rwho/*
 	if [ "$t" != '/var/rwho/*' ]; then
@@ -202,7 +228,7 @@ fi
 if checkyesno run_fsck; then
 	echo ""
 	echo "Checking filesystems:"
-	fsck -n | grep -v '^\*\* Phase'
+	fsck -n -f ${run_fsck_flags} | grep -v '^\*\* Phase'
 fi
 
 echo ""
@@ -217,18 +243,35 @@ if checkyesno run_rdist && [ -f /etc/Distfile ]; then
 fi
 
 if checkyesno run_security; then
-	SECOUT=$TMPDIR/sec
-	sh /etc/security 2>&1 > $SECOUT
-	if [ ! -s $SECOUT ]; then
-		echo "Nothing to report on $date" > $SECOUT
+	SECOUT="$DAILYDIR/sec"
+	sh /etc/security > "$SECOUT" 2>&1
+	if [ ! -s "$SECOUT" ]; then
+		if checkyesno send_empty_security; then
+			echo "Nothing to report on $date" > "$SECOUT"
+		else
+			echo ""
+			echo "Suppressing empty security report."
+		fi
 	fi
-	mail -s "$host daily insecurity output for $date" $MAILTO < $SECOUT
+	if [ -s "$SECOUT" ]; then
+		mail -s "$host daily insecurity output for $date" \
+		    "$MAILTO" < "$SECOUT"
+	fi
+fi
+
+if checkyesno run_skeyaudit; then
+	if [ -s /etc/skeykeys ]; then
+		echo ""
+		echo "Checking remaining s/key OTPs:"
+		skeyaudit
+	fi
 fi
 
 if [ -f /etc/daily.local ]; then
-	echo ""
-	echo "Running /etc/daily.local:"
-	. /etc/daily.local
+	( . /etc/daily.local ) > $TMP 2>&1
+	if [ -s $TMP ] ; then
+		printf "\nRunning /etc/daily.local:\n"
+		cat $TMP
+	fi
+	rm -f $TMP
 fi
-
-rm -rf $TMPDIR
diff --git a/etc/rc.d/network b/etc/rc.d/network
--- a/etc/rc.d/network
+++ b/etc/rc.d/network
@@ -1,17 +1,20 @@
 #!/bin/sh
 #
-# $NetBSD: network,v 1.4 2000/03/17 17:41:01 itojun Exp $
+# $NetBSD: network,v 1.57 2008/10/11 17:28:03 christos Exp $
 #
 
 # PROVIDE: network
-# REQUIRE: root mountcritlocal tty ipfilter
+# REQUIRE: ipfilter ipsec mountcritlocal root tty sysctl
+# BEFORE:  NETWORKING
 
-. /etc/rc.subr
-. /etc/rc.conf
+$_rc_subr_loaded . /etc/rc.subr
 
 name="network"
 start_cmd="network_start"
 stop_cmd="network_stop"
+
+nl='
+' # a newline
 
 network_start()
 {
@@ -22,21 +25,27 @@ network_start()
 	# If $hostname is set, use it for my Internet name,
 	# otherwise use /etc/myname
 	#
-	if [ -z "$hostname" -a -f /etc/myname ]; then
-		hostname=`cat /etc/myname`
+	if [ -z "$hostname" ] && [ -f /etc/myname ]; then
+		hostname=$(cat /etc/myname)
 	fi
 	if [ -n "$hostname" ]; then
 		echo "Hostname: $hostname"
 		hostname $hostname
 	else
-		warn "\$hostname not set."
+		# Don't warn about it if we're going to run
+		# DHCP later, as we will probably get the
+		# hostname at that time.
+		#
+		if ! checkyesno dhclient && [ -z "$(hostname)" ]; then
+			warn "\$hostname not set."
+		fi
 	fi
 
 	# Check $domainname first, then /etc/defaultdomain,
 	# for NIS/YP domain name
 	#
-	if [ -z "$domainname" -a -f /etc/defaultdomain ]; then
-		domainname=`cat /etc/defaultdomain`
+	if [ -z "$domainname" ] && [ -f /etc/defaultdomain ]; then
+		domainname=$(cat /etc/defaultdomain)
 	fi
 	if [ -n "$domainname" ]; then
 		echo "NIS domainname: $domainname"
@@ -45,26 +54,122 @@ network_start()
 
 	# Flush all routes just to make sure it is clean
 	if checkyesno flushroutes; then
-		route -n flush
+		/sbin/route -qn flush
 	fi
 
 	# Set the address for the first loopback interface, so that the
 	# auto-route from a newly configured interface's address to lo0
 	# works correctly.
 	#
-	# NOTE: obscure networking problems may occur if lo0 isn't configured...
+	# NOTE: obscure networking problems will occur if lo0 isn't configured.
 	#
-	ifconfig lo0 inet 127.0.0.1
+	/sbin/ifconfig lo0 inet 127.0.0.1
+
+	# According to RFC1122, 127.0.0.0/8 must not leave the node.
+	#
+	/sbin/route -q add -inet 127.0.0.0 -netmask 0xff000000 127.0.0.1 -reject
+
+	# IPv6 routing setups, and host/router mode selection.
+	#
+	if /sbin/ifconfig lo0 inet6 >/dev/null 2>&1; then
+		# We have IPv6 support in kernel.
+
+		# disallow link-local unicast dest without outgoing scope
+		# identifiers.
+		#
+		/sbin/route -q add -inet6 fe80:: -prefixlen 10 ::1 -reject
+
+		# disallow the use of the RFC3849 documentation address
+		#
+		/sbin/route -q add -inet6 2001:db8:: -prefixlen 32 ::1 -reject
+
+		# IPv6 site-local scoped address prefix (fec0::/10)
+		# has been deprecated by RFC3879.
+		#
+		if [ -n "$ip6sitelocal" ]; then
+			warn "\$ip6sitelocal is no longer valid"
+		fi
+
+		# disallow "internal" addresses to appear on the wire.
+		#
+		/sbin/route -q add -inet6 ::ffff:0.0.0.0 -prefixlen 96 ::1 -reject
+
+		# disallow packets to malicious IPv4 compatible prefix
+		#
+		/sbin/route -q add -inet6 ::224.0.0.0 -prefixlen 100 ::1 -reject
+		/sbin/route -q add -inet6 ::127.0.0.0 -prefixlen 104 ::1 -reject
+		/sbin/route -q add -inet6 ::0.0.0.0 -prefixlen 104 ::1 -reject
+		/sbin/route -q add -inet6 ::255.0.0.0 -prefixlen 104 ::1 -reject
+
+		# disallow packets to malicious 6to4 prefix
+		#
+		/sbin/route -q add -inet6 2002:e000:: -prefixlen 20 ::1 -reject
+		/sbin/route -q add -inet6 2002:7f00:: -prefixlen 24 ::1 -reject
+		/sbin/route -q add -inet6 2002:0000:: -prefixlen 24 ::1 -reject
+		/sbin/route -q add -inet6 2002:ff00:: -prefixlen 24 ::1 -reject
+
+		# Completely disallow packets to IPv4 compatible prefix.
+		# This may conflict with RFC1933 under following circumstances:
+		# (1) An IPv6-only KAME node tries to originate packets to IPv4
+		#     compatible destination.  The KAME node has no IPv4
+		#     compatible support.  Under RFC1933, it should transmit
+		#     native IPv6 packets toward IPv4 compatible destination,
+		#     hoping it would reach a router that forwards the packet
+		#     toward auto-tunnel interface.
+		# (2) An IPv6-only node originates a packet to IPv4 compatible
+		#     destination.  A KAME node is acting as an IPv6 router, and
+		#     asked to forward it.
+		# Due to rare use of IPv4 compatible address, and security
+		# issues with it, we disable it by default.
+		#
+		/sbin/route -q add -inet6 ::0.0.0.0 -prefixlen 96 ::1 -reject
+
+		/sbin/sysctl -qw net.inet6.ip6.forwarding=0
+		/sbin/sysctl -qw net.inet6.ip6.accept_rtadv=0
+
+		case $ip6mode in
+		router)
+			echo 'IPv6 mode: router'
+			/sbin/sysctl -qw net.inet6.ip6.forwarding=1
+
+			# disallow unique-local unicast forwarding without
+			# explicit configuration.
+			if ! checkyesno ip6uniquelocal; then
+				/sbin/route -q add -inet6 fc00:: -prefixlen 7 \
+				    ::1 -reject
+			fi
+			;;
+
+		autohost)
+			echo 'IPv6 mode: autoconfigured host'
+			/sbin/sysctl -qw net.inet6.ip6.accept_rtadv=1
+			;;
+
+		host)	
+			echo 'IPv6 mode: host'
+			;;
+
+		*)	warn "invalid \$ip6mode value "\"$ip6mode\"
+			;;
+
+		esac
+	fi
 
 	# Configure all of the network interfaces listed in $net_interfaces;
 	# if $auto_ifconfig is YES, grab all interfaces from ifconfig.
 	# In the following, "xxN" stands in for interface names, like "le0".
-	# For any interfaces that has an $ifconfig_xxN variable associated,
-	# we do "ifconfig xxN $ifconfig_xxN".
-	# If there is no such variable, we take the contents of the file
-	# /etc/ifconfig.xxN, and run "ifconfig xxN" repeatedly, using each
-	# line of the file as the arguments for a seperate "ifconfig"
-	# invocation.
+	#
+	# For any interfaces that has an $ifconfig_xxN variable
+	# associated, we break it into lines using ';' as a separator,
+	# then process it just like the contents of an /etc/ifconfig.xxN
+	# file.
+	#
+	# For each line from the $ifconfig_xxN variable or the
+	# /etc/ifconfig.xxN file, we ignore comments and blank lines,
+	# treat lines beginning with "!" as commands to execute, treat
+	# "dhcp" as a special case to invoke dhcpcd, and for any other
+	# line we run "ifconfig xxN", using each line of the file as the
+	# arguments for a separate "ifconfig" invocation.
 	#
 	# In order to configure an interface reasonably, you at the very least
 	# need to specify "[addr_family] [hostname]" (e.g "inet my.domain.org"),
@@ -77,28 +182,33 @@ network_start()
 	# configuration is possible:
 	#	inet 10.1.1.1 netmask 0xffffff00
 	#	inet 10.1.1.2 netmask 0xffffff00 alias
-	#	inet6 fec0::1 prefixlen 64 alias
+	#	inet6 2001:db8::1 prefixlen 64 alias
+	#
+	# You can put shell script fragment into /etc/ifconfig.xxN by
+	# starting a line with "!".  Refer to ifconfig.if(5) for details.
 	#
 	if [ "$net_interfaces" != NO ]; then
 		if checkyesno auto_ifconfig; then
-			tmp="`ifconfig -l`"
+			tmp=$(/sbin/ifconfig -l)
+			for cloner in $(/sbin/ifconfig -C 2>/dev/null); do
+				for int in /etc/ifconfig.${cloner}[0-9]*; do
+					[ ! -f $int ] && break
+					tmp="$tmp ${int##*.}"
+				done
+			done
 		else
 			tmp="$net_interfaces"
 		fi
 		echo -n 'Configuring network interfaces:'
 		for int in $tmp; do
-			eval `echo 'args=$ifconfig_'$int`
-			if [ -n "$args" ]; then
-				echo -n " $int"
-				ifconfig $int $args
-			elif [ -f /etc/ifconfig.$int ]; then
-				echo -n " $int"
-				(while read args; do
-					if [ -n "`eval echo '$args'`" ] ; then
-						ifconfig $int $args
-					fi
-				done) < /etc/ifconfig.$int
-			else
+			eval argslist=\$ifconfig_$int
+
+			# Skip interfaces that do not have explicit
+			# configuration information.  If auto_ifconfig is
+			# false then also warn about such interfaces.
+			#
+			if [ -z "$argslist" ] && ! [ -f /etc/ifconfig.$int ]
+			then
 				if ! checkyesno auto_ifconfig; then
 					echo
 					warn \
@@ -107,48 +217,103 @@ network_start()
 				fi
 				continue
 			fi
+
+			echo -n " $int"
+
+			# Create the interface if necessary.
+			# If the interface did not exist before,
+			# then also resync ipf(4).
+			#
+			if /sbin/ifconfig $int create 2>/dev/null && \
+			   checkyesno ipfilter; then
+				/sbin/ipf -y >/dev/null
+			fi
+
+			# If $ifconfig_xxN is empty, then use
+			# /etc/ifconfig.xxN, which we know exists due to
+			# an earlier test.
+			#
+			# If $ifconfig_xxN is non-empty and contains a
+			# newline, then just use it as is.  (This allows
+			# semicolons through unmolested.)
+			#
+			# If $ifconfig_xxN is non-empty and does not
+			# contain a newline, then convert all semicolons
+			# to newlines.
+			#
+			case "$argslist" in
+			'')
+				cat /etc/ifconfig.$int
+				;;
+			*"${nl}"*)
+				echo "$argslist"
+				;;
+			*)
+				(
+					set -o noglob
+					IFS=';'; set -- $argslist
+					#echo >&2 "[$#] [$1] [$2] [$3] [$4]"
+					IFS="$nl"; echo "$*"
+				)
+				;;
+			esac |
+			while read -r args; do
+				case "$args" in
+				''|"#"*|create)
+					;;
+				"!"*)
+					# Run arbitrary command in a subshell.
+					( eval "${args#*!}" )
+					;;
+				dhcp)
+					/sbin/dhcpcd -n ${dhcpcd_flags} $int
+					;;
+				*)
+					# Pass args to ifconfig.  Note
+					# that args may contain embedded
+					# shell metacharacters, such as
+					# "ssid 'foo;*>bar'". We eval
+					# one more time so that things
+					# like ssid "Columbia University" work.
+					(
+						set -o noglob
+						eval set -- $args
+						#echo >&2 "[$#] [$1] [$2] [$3]"
+						/sbin/ifconfig $int "$@"
+					)
+					;;
+				esac
+			done
 			configured_interfaces="$configured_interfaces $int"
 		done
 		echo "."
 	fi
 
-	# Check $defaultroute, then /etc/mygate, for the name of my gateway
-	# host. That name must be in /etc/hosts.
-	#
-	if [ -z "$defaultroute" -a -f /etc/mygate ]; then
-		defaultroute=`cat /etc/mygate`
-	fi
-	if [ -n "$defaultroute" ]; then
-		route add default $defaultroute
-	fi
+	echo -n "Adding interface aliases:"
 
 	# Check if each configured interface xxN has an $ifaliases_xxN variable
 	# associated, then configure additional IP addresses for that interface.
 	# The variable contains a list of "address netmask" pairs, with
 	# "netmask" set to "-" if the interface default netmask is to be used.
 	#
-	# Note that $ifaliases_xxN works only with certain configurations and
-	# considered not recommended.  Use /etc/ifconfig.xxN if possible.
-	# 
+	# Note that $ifaliases_xxN works only in certain cases and its
+	# use is not recommended.  Use /etc/ifconfig.xxN or multiple
+	# commands in $ifconfig_xxN instead.
 	#
-	if [ -n "$configured_interfaces" ]; then
-		echo "Adding interface aliases:"
-		done_aliases_message=yes
-	fi
-	for int in $configured_interfaces; do
-		eval `echo 'args=$ifaliases_'$int`
+	for int in lo0 $configured_interfaces; do
+		eval args=\$ifaliases_$int
 		if [ -n "$args" ]; then
 			set -- $args
 			while [ $# -ge 2 ]; do
 				addr=$1 ; net=$2 ; shift 2
 				if [ "$net" = "-" ]; then
-					ifconfig $int inet alias $addr
+					# for compatibility only, obsolete
+					/sbin/ifconfig $int inet alias $addr
 				else
-					ifconfig $int inet alias $addr \
+					/sbin/ifconfig $int inet alias $addr \
 					    netmask $net
 				fi
-				# Use loopback, not the wire
-				route add $addr 127.0.0.1
+				echo -n " $int:$addr"
 			done
 		fi
 	done
@@ -158,143 +323,77 @@ network_start()
 	# that contain
 	#	address interface netmask
 	#
-	# Note that /etc/ifaliases works only with certain cases only and its
-	# use is not recommended.  Use /etc/ifconfig.xxN instead.
-	#
+	# Note that /etc/ifaliases works only in certain cases and its
+	# use is not recommended.  Use /etc/ifconfig.xxN or multiple
+	# commands in $ifconfig_xxN instead.
 	#
 	if [ -f /etc/ifaliases ]; then
-	(
-		if [ "$done_aliases_message" != yes ]; then
-			echo "Adding interface aliases:"
-		fi
 		while read addr int net; do
 			if [ -z "$net" ]; then
-				ifconfig $int inet alias $addr
+				# for compatibility only, obsolete
+				/sbin/ifconfig $int inet alias $addr
 			else
-				ifconfig $int inet alias $addr netmask $net
+				/sbin/ifconfig $int inet alias $addr netmask $net
 			fi
-			# use loopback, not the wire
-			route add $addr 127.0.0.1
-		done
-	) < /etc/ifaliases
+		done < /etc/ifaliases
 	fi
 
-	# IPv6
-	# Note that manual configuration can be done in the above, using
-	# ifconfig.
+	echo "." # for "Adding interface aliases:"
+
+	# Check $defaultroute, then /etc/mygate, for the name or address
+	# of my IPv4 gateway host. If using a name, that name must be in
+	# /etc/hosts.
 	#
-	if ifconfig lo0 inet6 >/dev/null 2>&1; then
-		# We have IPv6 support in kernel.
+	if [ -z "$defaultroute" ] && [ -f /etc/mygate ]; then
+		defaultroute=$(cat /etc/mygate)
+	fi
+	if [ -n "$defaultroute" ]; then
+		/sbin/route add default $defaultroute
+	fi
 
-		# disallow link-local unicast dest without outgoing scope
-		# identifiers.
-		#
-		route add -inet6 fe80:: -prefixlen 10 ::1 -reject
-
-		# disallow site-local unicast dest without outgoing scope
-		# identifiers.
-		# If you configure site-locals without scope id (it is
-		# permissible config for routers that are not on scope
-		# boundary), you may want to comment the following one out.
-		#
-		route add -inet6 fec0:: -prefixlen 10 ::1 -reject
-
-		# disallow "internal" addresses to appear on the wire.
-		#
-		route add -inet6 ::ffff:0.0.0.0 -prefixlen 96 ::1 -reject
-
-		# disallow packets to malicious IPv4 compatible prefix
-		#
-		route add -inet6 ::224.0.0.0 -prefixlen 100 ::1 -reject
-		route add -inet6 ::127.0.0.0 -prefixlen 104 ::1 -reject
-		route add -inet6 ::0.0.0.0 -prefixlen 104 ::1 -reject
-		route add -inet6 ::255.0.0.0 -prefixlen 104 ::1 -reject
-
-		# disallow packets to malicious 6to4 prefix
-		#
-		route add -inet6 2002:e000:: -prefixlen 20 ::1 -reject
-		route add -inet6 2002:7f00:: -prefixlen 24 ::1 -reject
-		route add -inet6 2002:0000:: -prefixlen 24 ::1 -reject
-		route add -inet6 2002:ff00:: -prefixlen 24 ::1 -reject
-
-		# Completely disallow packets to IPv4 compatible prefix.
-		# This may conflict with RFC1933 under following circumstances:
-		# (1) An IPv6-only KAME node tries to originate packets to IPv4
-		#     comatible destination.  The KAME node has no IPv4
-		#     compatible support.  Under RFC1933, it should transmit
-		#     native IPv6 packets toward IPv4 compatible destination,
-		#     hoping it would reach a router that forwards the packet
-		#     toward auto-tunnel interface.
-		# (2) An IPv6-only node originates a packet to IPv4 compatible
-		#     destination.  A KAME node is acting as an IPv6 router, and
-		#     asked to forward it.
-		# Due to rare use of IPv4 compatible address, and security
-		# issues with it, we disable it by default.
-		#
-		route add -inet6 ::0.0.0.0 -prefixlen 96 ::1 -reject
-
-		sysctl -w net.inet6.ip6.forwarding=0 >/dev/null
-		sysctl -w net.inet6.ip6.accept_rtadv=0 >/dev/null
-
-		# backward compatibility
-		#
-		if [ -z "$ip6mode" -a -n "$ip6forwarding" ]; then
-			warn 'Please migrate to newer rc.conf' \
-			    '(use ip6mode, not ip6forwarding)'
-			if checkyesno ip6forwarding; then
-				ip6mode=router
-			else
-				if checkyesno rtsol; then
-					ip6mode=autohost
-				else
-					ip6mode=host
-				fi
-			fi
+	# Check $defaultroute6, then /etc/mygate6, for the name or address
+	# of my IPv6 gateway host. If using a name, that name must be in
+	# /etc/hosts.  Note that the gateway host address must be a link-local
+	# address if it is not using an stf* interface.
+	#
+	if [ -z "$defaultroute6" ] && [ -f /etc/mygate6 ]; then
+		defaultroute6=$(cat /etc/mygate6)
+	fi
+	if [ -n "$defaultroute6" ]; then
+		if [ "$ip6mode" = "autohost" ]; then
+			echo
+			warn \
+	    "ip6mode is set to 'autohost' and a v6 default route is also set."
 		fi
+		/sbin/route add -inet6 default $defaultroute6
+	fi
 
-		case $ip6mode in
-		router)
-			echo 'IPv6 mode: router'
-			sysctl -w net.inet6.ip6.forwarding=1 >/dev/null
-			;;
-
-		autohost)
-			echo 'IPv6 mode: autoconfigured host'
-			sysctl -w net.inet6.ip6.accept_rtadv=1 >/dev/null
-			if [ -n "$ip6defaultif" ]; then
-				ndp -I $ip6defaultif
-			fi
-			;;
-
-		host)	
-			echo 'IPv6 mode: host'
-			if [ -n "$ip6defaultif" ]; then
-				ndp -I $ip6defaultif
-			fi
-			;;
-
-		*)	echo 'WARNING: invalid value in ip6mode'
-			;;
-
-		esac
+	# IPv6 interface autoconfiguration.
+	#
+	if /sbin/ifconfig lo0 inet6 >/dev/null 2>&1; then
+		# wait till DAD is completed. always invoke it in case
+		# if are configured manually by ifconfig
+		#
+		dadcount=$(/sbin/sysctl -n net.inet6.ip6.dad_count 2>/dev/null)
+		sleep $dadcount
+		sleep 1
 
 		if checkyesno rtsol; then
 			if [ "$ip6mode" = "autohost" ]; then
 				echo 'Sending router solicitation...'
-				rtsol $rtsol_flags
+				/sbin/rtsol $rtsol_flags
 			else
 				echo
 				warn \
 			    "ip6mode must be set to 'autohost' to use rtsol."
 			fi
-		fi
 
-		# wait till DAD is completed. always invoke it in case if are
-		# configured manually by ifconfig
-		#
-		dadcount=`sysctl -n net.inet6.ip6.dad_count 2>/dev/null`
-		sleep $dadcount
-		sleep 1
+			# wait till DAD is completed, for global addresses
+			# configured by router advert message.
+			#
+			sleep $dadcount
+			sleep 1
+		fi
 	fi
 
 	# XXX this must die
@@ -312,28 +411,20 @@ network_stop()
 		sh /etc/netstart.local stop
 	fi
 
-	rtsolpid=`check_process rtsol`
-	if [ -n "$rtsolpid" ]; then
-		echo "Stopping rtsol (IPv6 router solicitation daemon)."
-		kill -TERM $rtsolpid
-	fi
-
 	echo "Deleting aliases."
 	if [ -f /etc/ifaliases ]; then
-	(
 		while read addr int net; do
-			ifconfig $int inet delete $addr
-		done
-	) < /etc/ifaliases
+			/sbin/ifconfig $int inet delete $addr
+		done < /etc/ifaliases
 	fi
 
-	for int in $configured_interfaces; do
-		eval `echo 'args=$ifaliases_'$int`
+	for int in $(/sbin/ifconfig -lu); do
+		eval args=\$ifaliases_$int
 		if [ -n "$args" ]; then
 			set -- $args
 			while [ $# -ge 2 ]; do
 				addr=$1 ; net=$2 ; shift 2
-				ifconfig $int inet delete $addr
+				/sbin/ifconfig $int inet delete $addr
 			done
 		fi
 	done
@@ -343,15 +434,21 @@ network_stop()
 	echo -n 'Downing network interfaces:'
 	if [ "$net_interfaces" != NO ]; then
 		if checkyesno auto_ifconfig; then
-			tmp="`ifconfig -l`"
+			tmp=$(/sbin/ifconfig -l)
 		else
 			tmp="$net_interfaces"
 		fi
 		for int in $tmp; do
-			eval `echo 'args=$ifconfig_'$int`
+			eval args=\$ifconfig_$int
 			if [ -n "$args" ] || [ -f /etc/ifconfig.$int ]; then
 				echo -n " $int"
-				ifconfig $int down
+				/sbin/dhcpcd -k $int 2> /dev/null
+				/sbin/ifconfig $int down
+				if /sbin/ifconfig $int destroy 2>/dev/null && \
+				   checkyesno ipfilter; then
+					# resync ipf(4)
+					/sbin/ipf -y >/dev/null
+				fi
 			fi
 		done
 		echo "."
@@ -359,8 +456,11 @@ network_stop()
 
 	# flush routes
 	#
-	route -n flush
+	/sbin/route -qn flush
 
 }
 
+load_rc_config $name
+load_rc_config_var dhclient dhclient
+load_rc_config_var ipfilter ipfilter
 run_rc_command "$1"
diff --git a/sys/arch/sparc64/conf/Makefile.sparc64 b/sys/arch/sparc64/conf/Makefile.sparc64
--- a/sys/arch/sparc64/conf/Makefile.sparc64
+++ b/sys/arch/sparc64/conf/Makefile.sparc64
@@ -1,4 +1,14 @@
-# 	$NetBSD: Makefile.sparc64,v 1.19 2000/01/31 22:47:11 eeh Exp $
+# 	$NetBSD: Makefile.sparc64,v 1.67 2008/08/30 13:23:55 martin Exp $
+
+#=========================================================================
+#
+#			***** WARNING ******
+#
+# ANYONE WHO CHANGES THIS MAKEFILE AND DOES NOT TEST BOTH A 32-BIT
+# AND 64-BIT KERNEL WILL BE SHOT.
+#
+#=========================================================================
+
 
 # Makefile for NetBSD
 #
@@ -12,85 +22,116 @@
 #	/sys/arch/sparc64/conf/Makefile.sparc64
 # after which config should be rerun for all machines of that type.
 #
-# N.B.: NO DEPENDENCIES ON FOLLOWING FLAGS ARE VISIBLE TO MAKEFILE
-#	IF YOU CHANGE THE DEFINITION OF ANY OF THESE RECOMPILE EVERYTHING
+# To specify debugging, add the config line: makeoptions DEBUG="-g"
+# A better way is to specify -g only for a few files.
 #
-# -DTRACE	compile in kernel tracing hooks
-# -DQUOTA	compile in file system quotas
+#	makeoptions DEBUGLIST="uvm* trap if_*"
 
-# DEBUG is set to -g if debugging.
-# PROF is set to -pg if profiling.
-
-.include "/etc/mk.conf"
-
-CC?=	cc
-.if exists(/usr/ccs/bin/ld)
-LD?=	/usr/ccs/bin/ld #Need to use Solaris ld to use the solaris loader
-.endif
-MKDEP?=	mkdep
-STRIP?=strip
-SIZE?=	size
-COPTS?= 	-O2
-#### Stuff for cross compiling
-NM?=nm
-LORDER?=lorder
-TSORT?=tsort
-
-
-# deal with Solaris vs. NetBSD build environments for now ..
-OS!=uname -s
-.if (${OS} == "NetBSD")
-USE_GENASSYM?=	no
+# Default to 32-bit.  Set the MACHINE_ARCH accordingly.
+#
+# You must also be using the correct toolchain or the kernel build
+# will fail.
+#
+LP64?=	no
+.if ${LP64} == "yes"
+MACHINE_ARCH=sparc64
 .else
-USE_GENASSYM?=	no
-AWK=nawk
+MACHINE_ARCH=sparc
 .endif
 
-.if exists(/usr/ccs/bin/ld)
-SVR4=-U__SVR4 -U__svr4__ -D__NetBSD__
-.else
-SVR4=
-.endif
+USETOOLS?=	no
+NEED_OWN_INSTALL_TARGET?=no
+.include <bsd.own.mk>
 
-# source tree is located via $S relative to the compilation directory
-.ifndef S
-S!=	cd ../../../..; pwd
-.endif
+##
+## (1) port identification
+##
 SPARC64=	$S/arch/sparc64
+GENASSYM_CONF=	${SPARC64}/sparc64/genassym.cf
 
-INCLUDES=	-I. -I$S/arch -I$S -nostdinc
-CPPFLAGS=	${INCLUDES} ${IDENT} ${PARAM} -D_KERNEL ${SVR4}
-CWARNFLAGS=	-Wimplicit -Wunused -Wswitch -Wcomment -Wtrigraphs -Wchar-subscripts -Wuninitialized -Wparentheses -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith
-#CWARNFLAGS=	-Werror -Wall -Wstrict-prototypes -Wmissing-prototypes
-CFLAGS=		${DEBUG} ${CWARNFLAGS} -O2 -Wa,-Av9a -mno-fpu
-AFLAGS=		-x assembler-with-cpp -Wa,-Av9a -traditional-cpp -D_LOCORE
-LINKFLAGS=	-N -p -Ttext f1000000 -e start >lderr
-STRIPFLAGS=	-g
+##
+## (2) compile settings
+##
+CPPFLAGS+=	-Dsparc64 -D__sparc64__
+.if ${LP64} == "yes"
+# 64-bit kernels
+CPPFLAGS+=	-D_LP64 -Wa,-Av9a
+AFLAGS+=	-Wa,-Av9a
+CC_NOOPT=	${NORMAL_C}
+.if defined(PROF)
+# Profiling is only supported in the medium low memory model.
+CFLAGS+=	-mcmodel=medlow
+.else
+# Since the kernel resides in the lower 32 bits, use medium low for now anyway.
+CFLAGS+=	-mcmodel=medlow
+.endif
+.else
+# 32-bit kernels
+CPPFLAGS+=	-m32 -Wa,-Av8plusa -mcpu=ultrasparc
+AFLAGS+=	-Wa,-Av8plusa
+# XXX
+# The sparc gcc version 3.3.3 (NetBSD nb1 20040301) does not compile this
+# file properly with higher optimizations
+CC_NOOPT=	${NORMAL_C:C/-O./-O0/}
+.endif
+CFLAGS+=	-mno-fpu
+AFLAGS+=	-x assembler-with-cpp -traditional-cpp
 
+##
+## (3) libkern and compat
+##
+# KERN_AS=	obj	# memcpy, memset, etc. are in locore.s
+
+##
+## (4) local objects, compile rules, and dependencies
+##
+MD_OBJS=	locore.o
+MD_CFILES=
+MD_SFILES=	${SPARC64}/sparc64/locore.s
+
+locore.o: ${SPARC64}/sparc64/locore.s assym.h
+	${NORMAL_S}
+
+##
+## (5) link settings
+##
+TEXTADDR?=	01000000
+LINKFORMAT=	-T ${SPARC64}/conf/${KERN_LDSCRIPT}
+.if ${LP64} == "yes"
+KERN_LDSCRIPT?= kern.ldscript
+.else
+KERN_LDSCRIPT?= kern32.ldscript
+.endif
+
+##
+## (6) port specific target dependencies
+##
+
+# depend on CPU configuration
+bwtwo.o cgsix.o cgthree.o cgtwo.o cons.o dma.o esp.o fb.o if_ie.o: Makefile
+ms.c obio.o zs.c autoconf.o clock.o cpu.o disksubr.o locore.o: Makefile
+machdep.o mem.o openprom.o pmap.o vm_machdep.o: Makefile
+
+cpu_in_cksum.o lock_stubs.o: assym.h
+
+##
+## (7) misc settings
+##
+
+# define .MAIN _before_ the make() check, so that implicit target
+# would be defined
+.MAIN: all
+
+.if make(depend) || make(all) || make(dependall)
+.BEGIN:
+	@rm -f sparc && \
+		ln -s $S/arch/sparc/include sparc
+.endif
+
+##
+## (8) config(8) generated machinery
+##
 %INCLUDES
-
-### find out what to use for libkern
-# KERN_AS=	obj	# bcopy, bzero, memcpy, memset, etc. are in locore.s
-.include "$S/lib/libkern/Makefile.inc"
-.ifndef PROF
-LIBKERN=	${KERNLIB}
-.else
-LIBKERN=	${KERNLIB_PROF}
-.endif
-
-### find out what to use for libcompat
-.include "$S/compat/common/Makefile.inc"
-.ifndef PROF
-LIBCOMPAT=	${COMPATLIB}
-.else
-LIBCOMPAT=	${COMPATLIB_PROF}
-.endif
-
-# compile rules: rules are named ${TYPE}_${SUFFIX} where TYPE is NORMAL or
-# HOSTED, and SUFFIX is the file suffix, capitalized (e.g. C for a .c file).
-
-NORMAL_C=	${CC} ${CFLAGS} ${CPPFLAGS} ${PROF} -c $<
-NORMAL_S=	${CC} ${AFLAGS} ${CPPFLAGS} -c $<
 
 %OBJS
 
@@ -98,124 +139,19 @@ NORMAL_S=	${CC} ${AFLAGS} ${CPPFLAGS} -c $<
 
 %SFILES
 
-# load lines for config "xxx" will be emitted as:
-# xxx: ${SYSTEM_DEP} swapxxx.o
-#	${SYSTEM_LD_HEAD}
-#	${SYSTEM_LD} swapxxx.o
-#	${SYSTEM_LD_TAIL}
-SYSTEM_OBJ=	locore.o \
-		param.o ioconf.o ${OBJS} ${LIBCOMPAT} ${LIBKERN}
-SYSTEM_DEP=	Makefile ${SYSTEM_OBJ}
-SYSTEM_LD_HEAD=	@rm -f $@
-SYSTEM_LD=	@echo ${LD} ${LINKFLAGS} -o $@ '$${SYSTEM_OBJ}' vers.o; \
-		${LD} ${LINKFLAGS} -o $@ ${SYSTEM_OBJ} vers.o
-SYSTEM_LD_TAIL=	@${SIZE} $@; chmod 755 $@
-
-DEBUG?=
-.if ${DEBUG} == "-g"
-LINKFLAGS+=	-X
-SYSTEM_LD_TAIL+=; \
-		echo mv -f $@ $@.gdb; mv -f $@ $@.gdb; \
-		echo ${STRIP} ${STRIPFLAGS} -o $@ $@.gdb; \
-		${STRIP} ${STRIPFLAGS} -o $@ $@.gdb
-.else
-LINKFLAGS+=	-S
-.endif
-
 %LOAD
 
-.if ${USE_GENASSYM} == "no"
-assym.h: $S/kern/genassym.sh ${SPARC64}/sparc64/genassym.cf
-	sh $S/kern/genassym.sh ${CC} ${CFLAGS} ${CPPFLAGS} ${PROF} \
-	    < ${SPARC64}/sparc64/genassym.cf > assym.h.tmp && \
-	mv -f assym.h.tmp assym.h
-.else
-HOSTED_CC=	${CC}
-HOSTED_CPPFLAGS=${CPPFLAGS:S/^-nostdinc$//}
-HOSTED_CFLAGS=	${CFLAGS}
-
-HOSTED_C=	${HOSTED_CC} ${HOSTED_CFLAGS} ${HOSTED_CPPFLAGS} -c $<
-
-assym.h: genassym
-	./genassym >assym.h
-
-genassym: genassym.o
-	${CC} -o $@ genassym.o
-
-genassym.o: ${SPARC64}/sparc64/genassym.c
-	${HOSTED_C}
-.endif
-
-param.c: $S/conf/param.c
-	rm -f param.c
-	cp $S/conf/param.c .
-
-param.o: param.c Makefile
-	${NORMAL_C}
-
-ioconf.o: ioconf.c
-	${NORMAL_C}
-
-newvers: ${SYSTEM_DEP} ${SYSTEM_SWAP_DEP}
-	sh $S/conf/newvers.sh
-	${CC} ${CFLAGS} ${CPPFLAGS} ${PROF} -c vers.c
-
-
-clean: cleankernel
-cleankernel:
-	rm -f eddep *netbsd netbsd.gdb tags *.[io] [a-z]*.s \
-	    [Ee]rrs lderr linterrs makelinks assym.h.tmp assym.h
-
-lint:
-	@lint -hbxncez -Dvolatile= ${CPPFLAGS} -UKGDB \
-	    ${SPARC64}/sparc64/Locore.c ${CFILES} \
-	    ioconf.c param.c | \
-	    grep -v 'static function .* unused'
-
-tags:
-	@echo "see $S/kern/Makefile for tags"
-
-links:
-	egrep '#if' ${CFILES} | sed -f $S/conf/defines | \
-	  sed -e 's/:.*//' -e 's/\.c/.o/' | sort -u > dontlink
-	echo ${CFILES} | tr -s ' ' '\12' | sed 's/\.c/.o/' | \
-	  sort -u | comm -23 - dontlink | \
-	  sed 's,../.*/\(.*.o\),rm -f \1; ln -s ../GENERIC/\1 \1,' > makelinks
-	sh makelinks && rm -f dontlink
-
-SRCS=	${SPARC64}/sparc64/locore.s \
-	param.c ioconf.c ${CFILES} ${SFILES}
-depend: .depend
-.depend: ${SRCS} assym.h param.c
-	${MKDEP} ${AFLAGS} ${CPPFLAGS} ${SPARC64}/sparc64/locore.s
-	${MKDEP} -a ${CFLAGS} ${CPPFLAGS} param.c ioconf.c ${CFILES}
-.if (${SFILES} != "")
-	${MKDEP} -a ${AFLAGS} ${CPPFLAGS} ${SFILES}
-.endif
-	sh $S/kern/genassym.sh ${MKDEP} -f assym.dep ${CFLAGS} \
-	  ${CPPFLAGS} < ${SPARC64}/sparc64/genassym.cf
-	@sed -e 's/.*\.o:.*\.c/assym.h:/' < assym.dep >> .depend
-	@rm -f assym.dep
-
-dependall: depend all
-
-
-# depend on root or device configuration
-autoconf.o conf.o: Makefile
-
-# depend on network or filesystem configuration 
-uipc_proto.o vfs_conf.o: Makefile 
-
-# depend on maxusers
-machdep.o: Makefile
-
-# depend on CPU configuration 
-bwtwo.o cgsix.o cgthree.o cgtwo.o cons.o dma.o esp.o fb.o if_ie.o: Makefile
-ms.c obio.o zs.c autoconf.o clock.o cpu.o disksubr.o locore.o: Makefile
-machdep.o mem.o openprom.o pmap.o vm_machdep.o: Makefile
-
-
-locore.o: ${SPARC64}/sparc64/locore.s assym.h
-	${NORMAL_S}
-
 %RULES
+
+## Include rules for Atheros WLAN
+.include "$S/contrib/dev/ath/netbsd/Makefile.ath.inc"
+
+##
+## (9) port independent kernel machinery
+##
+.include "$S/conf/Makefile.kern.inc"
+
+##
+## (10) Appending make options.
+##
+%MAKEOPTIONSAPPEND
