Initialize CVS branch phil-wifi
The per-file CVS branch roots do not exactly match a reconstructed source-branch commit.

diff --git a/distrib/sets/makesrctars b/distrib/sets/makesrctars
--- a/distrib/sets/makesrctars
+++ b/distrib/sets/makesrctars
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-#	$NetBSD: makesrctars,v 1.33 2007/03/23 02:57:30 jnemeth Exp $
+#	$NetBSD: makesrctars,v 1.41 2017/04/12 17:29:49 christos Exp $
 #
 # makesrctars srcdir setdir
 #	Create source tarballs in setdir from the source under srcdir.
@@ -12,28 +12,43 @@ rundir="$(dirname "$0")" # ${0%/*} isn't good enough when there's no "/"
 
 # set defaults
 xsrcdir=
+quiet=false
 
-GZIP=-9
+GZIP=-9n
 export GZIP
 
 usage()
 {
 	cat 1>&2 <<USAGE
-Usage: ${prog} [-N password/group dir] [-x xsrcdir] srcdir setdir
+Usage: ${prog} [-N password/group dir] [-q] [-x xsrcdir] [-y extsrcsrcdir] srcdir setdir
 	-N dir		location which contains master.passwd and group files
 			(defaults to \${srcdir}/etc)
+	-q		quiet operation
 	-x xsrcdir	build xsrc.tgz from xsrcdir
+	-y extsrcsrcdir	build extsrc.tgz from extsrcsrcdir
 	srcdir		location of sources
 	setdir		where to write the .tgz files to
 USAGE
 	exit 1
 }
 
+msg()
+{
+	$quiet || echo $*
+}
+
+
 # handle args
-while getopts N:x: ch; do
+while getopts N:qx:y: ch; do
 	case ${ch} in
+	q)
+		quiet=true
+		;;
 	x)
 		xsrcdir="${OPTARG}"
+		;;
+	y)
+		extsrcsrcdir="${OPTARG}"
 		;;
 	N)
 		PASSWD="${OPTARG}"
@@ -53,7 +68,7 @@ setdir="$2"
 : ${PASSWD:="${srcdir}/etc"}
 
 if [ ! -d "${setdir}" ]; then
-	echo "${setdir} is not a directory"
+	echo >&2 "${prog}: ${setdir} is not a directory"
 	exit 1
 fi
 
@@ -64,7 +79,7 @@ makeset()
 	dir="$1"
 	shift
 	intmp="/tmp/in$$"
-	echo "Creating ${set}"
+	msg "Creating ${set}"
 	if [ "${dir}" != "." ]; then
 		cd "${dir}"
 		srcprefix="${srcprefix}/${dir}"
@@ -76,13 +91,13 @@ makeset()
 		egrep='.'
 	fi
 	set -f
-	${MTREE} -c -X "${intmp}" | ${MTREE} -C -k type | \
+	${MTREE} -c -X "${intmp}" | ${MTREE} -CS -k type | \
 		${EGREP} -v 'type=link' | ${EGREP} ${egrep} | \
 		${SED} -e 's:type=file:& mode=0664:' \
 			-e 's:type=dir:& mode=0775:' \
 			-e 's:$: uname=root gname=wsrc:' \
 			-e '/\/move-if-change /s:\(mode\)=[0-9]*:\1=0775:' \
-			-e '/^\.\/build.sh /s:\(mode\)=[0-9]*:\1=0775:' | \
+			-e '/^\.\/.*[.-]sh /s:\(mode\)=[0-9]*:\1=0775:' | \
 		${PAX} -M -N "${PASSWD}" -w -d -s'|^\.|'"${srcprefix}"'|' | \
 		${GZIP_CMD} > "${setdir}/${set}"
 	rm -f "${intmp}"
@@ -93,16 +108,16 @@ makeset()
 #
 
 if ! cd "${srcdir}"; then
-	echo "Can't chdir to ${srcdir}"
+	echo >&2 "${prog}: can't chdir to ${srcdir}"
 	exit 1
 fi
 
 srcprefix=usr/src
 export setdir MTREE PAX CKSUM GZIP PASSWD srcprefix
 
-makeset src . -v '^\.\/gnu|^\.\/share|^\.\/sys|^\.\/usr\.bin\/config|^\.\/common'
+makeset src . -v '^\.\/common|^\.\/external\/gpl2|^\.\/external\/gpl3|^\.\/share|^\.\/sys|^\.\/usr\.bin\/config'
 
-makeset gnusrc gnu
+makeset gnusrc . -e '^\..type=dir|^\.\/external.type=dir|^\.\/external\/gpl2|^\.\/external\/gpl3'
 
 makeset syssrc . -e '^\..type=dir|^\.\/sys|^\.\/usr\.bin.type=dir|^\.\/usr\.bin\/config|^\.\/common'
 
@@ -113,7 +128,7 @@ makeset sharesrc share
 #
 if [ -n "${xsrcdir}" ]; then
 	if ! cd "${xsrcdir}"; then
-		echo "Can't chdir to ${xsrcdir}"
+		echo >&2 "${prog}: can't chdir to ${xsrcdir}"
 		exit 1
 	fi
 	srcprefix=usr/xsrc
@@ -121,12 +136,21 @@ if [ -n "${xsrcdir}" ]; then
 fi
 
 
-echo "Creating checksum files"
+# create extsrc sets
+#
+if [ -n "${extsrcsrcdir}" ]; then
+	if ! cd "${extsrcsrcdir}"; then
+		echo >&2 "${prog}: can't chdir to ${extsrcsrcdir}"
+		exit 1
+	fi
+	srcprefix=usr/extsrc
+	makeset extsrc .
+fi
+
+
+msg "Creating checksum files"
 (cd "${setdir}"
-	${CKSUM} -o1 *.tgz > BSDSUM
-	${CKSUM}     *.tgz > CKSUM
 	${CKSUM} -a md5  *.tgz > MD5
-	${CKSUM} -o2 *.tgz > SYSVSUM
 	${CKSUM} -a sha512 *.tgz > SHA512
 )
 exit 0
diff --git a/etc/rc.d/swap1 b/etc/rc.d/swap1
--- a/etc/rc.d/swap1
+++ b/etc/rc.d/swap1
@@ -1,10 +1,10 @@
 #!/bin/sh
 #
-# $NetBSD: swap1,v 1.9 2004/08/13 18:08:03 mycroft Exp $
+# $NetBSD: swap1,v 1.12 2015/04/20 18:01:46 prlw1 Exp $
 #
 
 # PROVIDE: localswap
-# REQUIRE: disks
+# REQUIRE: DISKS root
 # KEYWORD: shutdown
 
 $_rc_subr_loaded . /etc/rc.subr
@@ -18,8 +18,11 @@ stop_cmd="swap1_stop"
 #
 swap1_start()
 {
+	# Treat exit status 2 from swapctl(8) as successful; it means
+	# "no error, but no suitable swap devices were configured".
+	#
 	if ! checkyesno no_swap; then
-		swapctl -A -t blk
+		swapctl -A -t blk || [ $? = 2 ]
 	fi
 }
 
@@ -28,8 +31,10 @@ swap1_start()
 swap1_stop()
 {
 	if checkyesno swapoff || [ -n "$rc_force" ]; then
+		echo "Forcibly unmounting tmpfs filesystems"
+		umount -aft tmpfs
 		echo "Removing block-type swap devices"
-		swapctl -U -t blk
+		swapctl -U -t blk || [ $? = 2 ]
 	fi
 }
 
diff --git a/etc/security b/etc/security
--- a/etc/security
+++ b/etc/security
@@ -1,6 +1,6 @@
 #!/bin/sh -
 #
-#	$NetBSD: security,v 1.105 2007/11/23 15:51:27 dholland Exp $
+#	$NetBSD: security,v 1.122 2018/01/06 23:44:06 mlelstv Exp $
 #	from: @(#)security	8.1 (Berkeley) 6/9/93
 #
 
@@ -21,13 +21,16 @@ TZ=UTC; export TZ
 if [ -s /etc/security.conf ]; then
 	. /etc/security.conf
 fi
+if [ -s /etc/pkgpath.conf ]; then
+	. /etc/pkgpath.conf
+fi
 
 # Set reasonable defaults (if they're not set in security.conf)
 #
 backup_dir=${backup_dir:-/var/backups}
-pkgdb_dir=${pkgdb_dir:-/var/db/pkg}
 max_loginlen=${max_loginlen:-8}
 max_grouplen=${max_grouplen:-8}
+pkg_admin=${pkg_admin:-/usr/sbin/pkg_admin}
 pkg_info=${pkg_info:-/usr/sbin/pkg_info}
 
 # Other configurable variables
@@ -58,10 +61,20 @@ MPBYPATH=mpbypath.$$
 LIST=list.$$
 OUTPUT=output.$$
 LABELS=labels.$$
+LVM_LABELS=lvm.$$
 PKGS=pkgs.$$
 CHANGEFILES=changefiles.$$
 SPECIALSPEC=specialspec.$$
 
+if [ -n "${pkgdb_dir}" ]; then
+	echo "WARNING: Setting pkgdb_dir in security.conf(5) is deprecated"
+	echo "WARNING: Please define PKG_DBDIR in pkg_install.conf(5) instead"
+	_compat_K_flag="-K ${pkgdb_dir}"
+fi
+
+have_pkgs() {
+	$pkg_info ${_compat_K_flag} -q -E '*'
+}
 
 # migrate_file old new
 #	Determine if the "${old}" path name needs to be migrated to the
@@ -104,7 +117,7 @@ migrate_file()
 
 # backup_and_diff file printdiff
 #	Determine if file needs backing up, and if so, do it.
-#	If printdiff is yes, display the diffs, otherwise 
+#	If printdiff is yes, display the diffs, otherwise
 #	just print a message saying "[changes omitted]".
 #
 backup_and_diff()
@@ -181,8 +194,8 @@ done | mtree -CM -k all > $SPECIALSPEC || exit 1
 # Check the master password file syntax.
 #
 if checkyesno check_passwd; then
-        # XXX: the sense of permit_star is reversed; the code works as
-        # implemented, but usage needs to be negated.
+	# XXX: the sense of permit_star is reversed; the code works as
+	# implemented, but usage needs to be negated.
 	checkyesno check_passwd_permit_star && permit_star=0 || permit_star=1
 	checkyesno check_passwd_permit_nonalpha \
 		 && permit_nonalpha=1 || permit_nonalpha=0
@@ -278,14 +291,18 @@ if checkyesno check_passwd; then
 		column $OUTPUT
 	fi
 
-# To not exclude 'toor', a standard duplicate root account, from the duplicate
-# account test, uncomment the line below (without egrep in it)and comment
-# out the line (with egrep in it) below it.
-#
-#	< $MPBYUID uniq -d -f 1 | awk '{ print $2 }' > $TMP2
-	< $MPBYUID egrep -v '^toor ' | uniq -d -f 1 | awk '{ print $2 }' > $TMP2
+	awk -v "permit_dups_list=$check_passwd_permit_dups" \
+	'
+	BEGIN {
+		split(permit_dups_list, a);
+		for (i in a) permit_dups[a[i]]++;
+	}
+	{
+		if (!permit_dups[$1])
+			print $2;
+	}' < $MPBYUID | uniq -d > $TMP2
 	if [ -s $TMP2 ] ; then
-		printf "\n$MP has duplicate user id's.\n"
+		printf "\n$MP has duplicate user ids.\n"
 		while read uid; do
 			grep -w $uid $MPBYUID
 		done < $TMP2 | column
@@ -320,9 +337,17 @@ if checkyesno check_group; then
 	fi
 
 	awk -F: '{ print $1 }' $GRP | sort | uniq -d > $OUTPUT
-	if [ -s $OUTPUT ] ; then
+	dupgroups=""
+	for group in $(cat $OUTPUT) ; do
+		gcount=$(awk -F: "/$group/ { print \$1,\$3 }" $GRP |
+			sort -u | wc -l)
+		if [ $gcount -gt 1 ]; then
+			dupgroups="$dupgroups $group"
+		fi
+	done
+	if [ ! -z $dupgroups ] ; then
 		printf "\n$GRP has duplicate group names.\n"
-		column $OUTPUT
+		printf "$dupgroups\n"
 	fi
 fi
 
@@ -399,8 +424,8 @@ end-of-csh
 			unset PATH
 			/bin/sh << end-of-sh > /dev/null 2>&1
 				. $i
-				list=\`echo \$PATH | /usr/bin/sed -e \
-				    's/^:/.:/;s/:$/:./;s/::/:.:/g;s/:/ /g'\`
+				list=\$(echo \$PATH | /usr/bin/sed -e \
+				    's/^:/.:/;s/:$/:./;s/::/:.:/g;s/:/ /g')
 				/bin/ls -ldgT \$list > $TMP1
 end-of-sh
 			export PATH=$SAVE_PATH
@@ -432,7 +457,7 @@ fi
 # Root and uucp should both be in /etc/ftpusers.
 #
 if checkyesno check_ftpusers; then
-	list="uucp "`awk '$2 == 0 { print $1 }' $MPBYUID`
+	list="uucp "$(awk '$2 == 0 { print $1 }' $MPBYUID)
 	for i in $list; do
 		if /usr/libexec/ftpd -C $i ; then
 			printf "\t$i is not denied\n"
@@ -472,7 +497,7 @@ if checkyesno check_rhosts; then
 	sort -k2 |
 	while read uid homedir; do
 		if [ -f ${homedir}/.rhosts ] ; then
-			rhost=`ls -ldgT ${homedir}/.rhosts`
+			rhost=$(ls -ldgT ${homedir}/.rhosts)
 			printf -- "$uid: $rhost\n"
 		fi
 	done > $OUTPUT
@@ -501,12 +526,17 @@ if checkyesno check_homes; then
 		permit_usergroups=1 || permit_usergroups=0
 	while read uid homedir; do
 		if [ -d ${homedir}/ ] ; then
-			file=`ls -ldgT ${homedir}`
+			file=$(ls -ldgT ${homedir})
 			printf -- "$uid $file\n"
 		fi
 	done < $MPBYPATH |
-	awk -v "usergroups=$permit_usergroups" '
-	     $1 != $4 && $4 != "root" \
+	awk -v "usergroups=$permit_usergroups" \
+	    -v "permit_owners_list=$check_homes_permit_other_owner"  '
+	     BEGIN {
+		split(permit_owners_list, a);
+		for (i in a) permit_owners[a[i]]++;
+	     }
+	     $1 != $4 && $4 != "root" && !permit_owners[$1] \
 		{ print "user " $1 " home directory is owned by " $4 }
 	     $2 ~ /^d....w/ && (!usergroups || $5 != $1) \
 		{ print "user " $1 " home directory is group writable" }
@@ -524,12 +554,17 @@ if checkyesno check_homes; then
 		for f in $list ; do
 			file=${homedir}/${f}
 			if [ -f $file ] ; then
-				printf -- "$uid $f `ls -ldgT $file`\n"
+				printf -- "$uid $f $(ls -ldgT $file)\n"
 			fi
 		done
 	done < $MPBYPATH |
-	awk  -v "usergroups=$permit_usergroups" '
-	     $1 != $5 && $5 != "root" \
+	awk -v "usergroups=$permit_usergroups" \
+	    -v "permit_owners_list=$check_homes_permit_other_owner"  '
+	     BEGIN {
+		split(permit_owners_list, a);
+		for (i in a) permit_owners[a[i]]++;
+	     }
+	     $1 != $5 && $5 != "root" && !permit_owners[$1] \
 		{ print "user " $1 " " $2 " file is owned by " $5 }
 	     $3 ~ /^-...r/ && (!usergroups || $6 != $1) \
 		{ print "user " $1 " " $2 " file is group readable" }
@@ -553,12 +588,17 @@ if checkyesno check_homes; then
 		for f in $list ; do
 			file=${homedir}/${f}
 			if [ -f $file ] ; then
-				printf -- "$uid $f `ls -ldgT $file`\n"
+				printf -- "$uid $f $(ls -ldgT $file)\n"
 			fi
 		done
 	done < $MPBYPATH |
-	awk -v "usergroups=$permit_usergroups" '
-	     $1 != $5 && $5 != "root" \
+	awk -v "usergroups=$permit_usergroups" \
+	    -v "permit_owners_list=$check_homes_permit_other_owner"  '
+	     BEGIN {
+		split(permit_owners_list, a);
+		for (i in a) permit_owners[a[i]]++;
+	     }
+	     $1 != $5 && $5 != "root" && !permit_owners[$1] \
 		{ print "user " $1 " " $2 " file is owned by " $5 }
 	     $3 ~ /^-....w/ && (!usergroups || $6 != $1) \
 		{ print "user " $1 " " $2 " file is group writable" }
@@ -840,7 +880,7 @@ if checkyesno check_mtree; then
 
 	for file in /etc/mtree/*.secure; do
 		[ $file = '/etc/mtree/*.secure' ] && continue
-		tree=`sed -n -e '3s/.* //p' -e 3q $file`
+		tree=$(sed -n -e '3s/.* //p' -e 3q $file)
 		mtree $check_mtree_flags -f $file -p $tree > $TMP1
 		if [ -s $TMP1 ]; then
 			printf "\nChecking $tree:\n"
@@ -857,50 +897,99 @@ fi
 #
 if checkyesno check_disklabels; then
 		# migrate old disklabels
-	for file in `ls -1d $backup_dir/$backup_dir/disklabel.* \
-	    $backup_dir/disklabel.* 2>/dev/null`; do
+	for file in $(ls -1d $backup_dir/$backup_dir/disklabel.* \
+	    $backup_dir/disklabel.* 2>/dev/null); do
 		migrate_file "$file" "$work_dir/${file##*/}"
 	done
 
-		# generate list of old disklabels, fdisks & wedges and remove them
-	ls -1d $work_dir/disklabel.* $work_dir/fdisk.* $work_dir/wedges.* 2>/dev/null |
+		# generate list of old disklabels, fdisks & wedges,
+		# and remove them
+	ls -1d $work_dir/disklabel.* $work_dir/fdisk.* $work_dir/wedges.* \
+	    2>/dev/null |
 	    egrep -v '\.(backup|current)(,v)?$' > $LABELS
 	xargs rm < $LABELS
 
-		# generate disklabels of all disks excluding:	cd dk fd md st
-	disks=`iostat -x | awk 'NR > 1 && $1 !~ /^[cfm]d|dk|st|nfs/ { print $1; }'`
+	disks="$(/sbin/sysctl -n hw.iostatnames)"
+
+		# generate disklabels of all disks excluding:	cd fd md dk st
+		# nfs and "device" (the header of iostat)
 	for i in $disks; do
-		disklabel $i > "$work_dir/disklabel.$i" 2>/dev/null
+		case $i in
+		[cfm]d[0-9]*|dk[0-9]*|st[0-9]*|nfs[0-9]*)
+			;;
+		*)
+			if disklabel $i > /dev/null 2>&1; then
+				disklabel $i > "$work_dir/disklabel.$i"
+			fi
+			;;
+		esac
 	done
 
 		# if fdisk is available, generate fdisks for:	ed ld sd wd
 	if [ -x /sbin/fdisk ]; then
-		disks=`iostat -x| awk 'NR > 1 && $1 ~ /^[elsw]d/ { print $1; }'`
 		for i in $disks; do
-			/sbin/fdisk $i > "$work_dir/fdisk.$i" 2>/dev/null
+			case $i in
+			[elsw]d[0-9]*)
+				/sbin/fdisk $i > "$work_dir/fdisk.$i" \
+				    2>/dev/null
+				;;
+			esac
 		done
 	fi
 
-		# if dkctl is available, generate dkctl listwedges for:	ed ld sd wd cgd ofdisk ra rl raid
+		# if dkctl is available, generate dkctl listwedges
+		# for:	ed ld sd wd cgd ofdisk ra rl raid
 	if [ -x /sbin/dkctl ]; then
-		disks=`iostat -x| awk 'NR > 1 && $1 ~ /^[elsw]d|cgd|ofdisk|r[al]|raid/ { print $1; }'`
 		for i in $disks; do
-			/sbin/dkctl $i listwedges > "$work_dir/wedges.$i" 2>/dev/null
+			case $i in
+			[elsw]d[0-9]*|cgd[0-9]*|ofdisk[0-9]*|r[al][0-9]*|raid[0-9]*)
+				if /sbin/dkctl $i listwedges |
+				     grep -qe '[0-9] wedges:'; then
+					/sbin/dkctl $i listwedges \
+					    > "$work_dir/wedges.$i" 2>/dev/null
+				fi
+				;;
+			esac
+		done
+	fi
+
+		# if raidctl is available, generate raidctls for:	raid
+	if [ -x /sbin/raidctl ]; then
+		disks=$(iostat -x | awk 'NR > 1 && $1 ~ /^raid/ { print $1; }')
+		for i in $disks; do
+			/sbin/raidctl -G $i > "$work_dir/raidconf.$i" \
+				2>/dev/null
 		done
 	fi
 
 		# append list of new disklabels, fdisks and wedges
-	ls -1d $work_dir/disklabel.* $work_dir/fdisk.* $work_dir/wedges.* 2>/dev/null |
+	ls -1d $work_dir/disklabel.* $work_dir/fdisk.* $work_dir/wedges.* \
+	    $work_dir/raidconf.* 2>/dev/null |
 	    egrep -v '\.(backup|current)(,v)?$' >> $LABELS
 	CHANGELIST="$LABELS $CHANGELIST"
 fi
 
+if checkyesno check_lvm; then
+		# generate list of existing LVM elements Physical Volumes,
+		# Volume Groups and Logical Volumes.
+	if [ -x /sbin/lvm ]; then
+		lvm pvdisplay -m >"$work_dir/lvm.pv" 2>/dev/null
+		lvm vgdisplay -m >"$work_dir/lvm.vg" 2>/dev/null
+		lvm lvdisplay -m >"$work_dir/lvm.lv" 2>/dev/null
+	fi
+	ls -1d $work_dir/lvm.* 2>/dev/null |
+	    egrep -v '\.(backup|current)(,v)?$'>> $LVM_LABELS
+	CHANGELIST="$CHANGELIST $LVM_LABELS"
+fi
+
 # Check for changes in the list of installed pkgs
 #
-if checkyesno check_pkgs && [ -d $pkgdb_dir ]; then
+if checkyesno check_pkgs && have_pkgs; then
 	pkgs=$work_dir/pkgs
 	migrate_file "$backup_dir/pkgs" "$pkgs"
-	(	cd $pkgdb_dir
+	pkg_dbdir=$(${pkg_admin} config-var PKG_DBDIR)
+	: ${pkg_dbdir:=/var/db/pkg}
+	(	cd $pkg_dbdir
 		$pkg_info | sort
 		echo ""
 		find . \( -name +REQUIRED_BY -o -name +CONTENTS \) -print0 |
@@ -928,6 +1017,8 @@ if checkyesno check_changelist ; then
 		echo "/etc/raid*.conf"
 		echo "/etc/rc.d/*"
 		echo "/etc/rc.conf.d/*"
+		echo "/etc/lvm/backup/*"
+		echo "/etc/lvm/archive/*"
 
 		# Add /etc/changelist
 		#
@@ -941,7 +1032,7 @@ if checkyesno check_changelist ; then
 				#
 			ls -1d $(echo $backup_dir/${file}.current) 2>/dev/null \
 			    | sed "s,^$backup_dir/,, ; s,\.current$,,"
-				
+
 				# ... expand possible files
 				#
 			ls -1d $(echo $file) 2>/dev/null
@@ -975,6 +1066,24 @@ if [ -n "$CHANGELIST" ]; then
 	comm -23 $TMP1 $TMP2 | while read file; do
 		backup_and_diff "$file" yes
 	done
+fi
+
+if have_pkgs; then
+	if checkyesno check_pkg_vulnerabilities; then
+		${pkg_admin} ${_compat_K_flag} audit >${OUTPUT} 2>&1
+		if [ -s ${OUTPUT} ]; then
+			printf "\nInstalled vulnerable packages:\n"
+			cat ${OUTPUT}
+		fi
+	fi
+
+	if checkyesno check_pkg_signatures; then
+		${pkg_admin} ${_compat_K_flag} check >${OUTPUT} 2>&1
+		if [ $? -ne 0 ]; then
+			printf "\nFiles with invalid signatures:\n"
+			cat ${OUTPUT}
+		fi
+	fi
 fi
 
 if [ -f /etc/security.local ]; then
diff --git a/games/wtf/wtf b/games/wtf/wtf
--- a/games/wtf/wtf
+++ b/games/wtf/wtf
@@ -1,95 +1,113 @@
 #!/bin/sh
 #
-#	$NetBSD: wtf,v 1.15 2007/08/06 21:14:36 hubertf Exp $
+#	$NetBSD: wtf,v 1.24 2018/03/07 08:25:43 eadler Exp $
 #
 # Public domain
 #
 
-PROGNAME=`basename $0`
+PROGNAME="$(basename "$0")"
+offensive=false
 
 usage() {
-	echo "usage: $PROGNAME [-f dbfile] [is] <acronym>"
+	echo "usage: $PROGNAME [-o] [-f dbfile] [is] term ..."
 	exit 1
 }
 
-acronyms=${ACRONYMDB:-`ls /usr/share/misc/acronyms* 2>/dev/null`}
+while getopts f:o f
+do
+	case "$f" in
+	o)	offensive=true
+		;;
+	f)
+		acronyms="$OPTARG $acronyms"
+		;;
+	*)
+		usage
+		;;
+	esac
+done
 
-if [ "$acronyms" = "" ]; then
-	echo "$PROGNAME: acronyms database not found!" >&2
+shift "$(expr "$OPTIND" - 1)"
+
+if [ "$1" = "is" ]; then
+	if [ $# -gt 1 ] ; then
+		shift
+	fi
+fi
+
+if [ -z "$1" ]; then
+	usage
+fi
+
+if [ -z "$acronyms" ]; then
+	if [ -z "$ACRONYMDB" ]; then
+		for f in /usr/share/misc/acronyms*; do
+			case $f in
+			*-o)
+				if $offensive; then
+					acronyms="$acronyms $f"
+				fi
+				;;
+			*)
+				acronyms="$acronyms $f"
+				;;
+			esac
+		done
+	else
+		acronyms="$ACRONYMDB"
+	fi
+fi
+
+if [ -z "$acronyms" ]; then
+	echo "$PROGNAME: acronym database not found!" >&2
 	exit 1
 fi
 
-args=`getopt f: $*`
-if [ $? -ne 0 ]; then
-	usage
-fi
-set -- $args
-while [ $# -gt 0 ]; do
-	case "$1" in
-		-f)
-			acronyms=$2; shift
-			;;
-		--)
-			shift; break
-			;;
-	esac
-	shift
-done
 
-if [ "$1" = "is" ] ; then
-	shift
-fi
-
-if [ $# -lt 1 ] ; then
-	usage
-fi
-
-for f in $acronyms
-do
-	if [ ! -f $f ]; then
-		echo "$PROGNAME: cannot open acronyms database file \`$f'" >&2
+for f in $acronyms; do
+	if [ ! -f "$f" ]; then
+		echo "$PROGNAME: cannot open acronym database file \`$f'" >&2
 		exit 1
 	fi
 done
 
 rv=0
-while [ $# -gt 0 ] ; do
-	# Search acronyms list first
-	target=`echo $1 | tr '[a-z]' '[A-Z]'`
-	ans=`fgrep -h $target $acronyms 2>/dev/null \
-	     | sed -ne "\|^$target[[:space:]]|s|^$target[[:space:]]*||p"`
-	if [ "$ans" != "" ] ; then
+for i; do
+	# Search acronym list first
+  target="$(echo "$i" | tr '[:lower:]' '[:upper:]')"
+	ans="$(fgrep -h "$target" $acronyms 2>/dev/null \
+	     | sed -ne "\|^$target[[:space:]]|s|^$target[[:space:]]*||p")"
+	if [ -n "$ans" ] ; then
 		echo "$target: $ans"
-		shift ; continue
+		continue
 	fi
 
 	# Try whatis(1) next
-	ans=`whatis $1 2>/dev/null`
-	if [ $? -eq 0 ] ; then
+	ans="$(whatis "$i" 2>/dev/null)"
+	if [ $? -eq 0 ]; then
 		echo "$ans" | sort -u
-		shift ; continue
+		continue
 	fi
 
 	# Try pkg_info(1) next
-	ans=`pkg_info -qc $1 2> /dev/null`
-	if [ $? -eq 0 ] ; then
-		echo "$1: $ans"
-		shift ; continue
+	ans="$(pkg_info -qc "$i" 2> /dev/null)"
+	if [ $? -eq 0 ]; then
+		echo "$i: $ans"
+		continue
 	fi
 
-	# Try querying pkgsrc's help facility next
-	if [ -f ../../mk/bsd.pkg.mk ] ; then
-		ans=`make help topic="$1"`
-		if [ $? -eq 0 ] ; then
-			echo "$1: $ans"
-			shift ; continue
+	# If called from pkgsrc package directory,
+	# try querying pkgsrc's help facility next
+	if [ -f ../../mk/bsd.pkg.mk ]; then
+		ans="$(make help topic="$i")"
+		if [ "$ans" != "No help found for $i." ]; then
+			echo "$i: $ans"
+			continue
 		fi
 	fi
 
 	# Give up!
-	echo "$PROGNAME: I don't know what $1 means!" 1>&2
+	echo "$PROGNAME: I don't know what \`$i' means!" 1>&2
 	rv=1
-	
-	shift
 done
 exit $rv
