Initialize CVS branch matt-nb6-plus
The per-file CVS branch roots do not exactly match a reconstructed source-branch commit.

diff --git a/etc/security b/etc/security
--- a/etc/security
+++ b/etc/security
@@ -1,6 +1,6 @@
 #!/bin/sh -
 #
-#	$NetBSD: security,v 1.106 2009/01/27 10:32:18 haad Exp $
+#	$NetBSD: security,v 1.110 2011/03/02 17:00:28 christos Exp $
 #	from: @(#)security	8.1 (Berkeley) 6/9/93
 #
 
@@ -25,7 +25,6 @@ fi
 # Set reasonable defaults (if they're not set in security.conf)
 #
 backup_dir=${backup_dir:-/var/backups}
-pkgdb_dir=${pkgdb_dir:-/var/db/pkg}
 max_loginlen=${max_loginlen:-8}
 max_grouplen=${max_grouplen:-8}
 pkg_info=${pkg_info:-/usr/sbin/pkg_info}
@@ -62,6 +61,16 @@ LVM_LABELS=lvm.$$
 PKGS=pkgs.$$
 CHANGEFILES=changefiles.$$
 SPECIALSPEC=specialspec.$$
+
+if [ -n "${pkgdb_dir}" ]; then
+    echo "WARNING: Setting pkgdb_dir in security.conf(5) is deprecated"
+    echo "WARNING: Please define PKG_DBDIR in pkg_install.conf(5) instead"
+    _compat_K_flag="-K ${pkgdb_dir}"
+fi
+
+have_pkgs() {
+	$pkg_info ${_compat_K_flag} -q -E '*'
+}
 
 # migrate_file old new
 #	Determine if the "${old}" path name needs to be migrated to the
@@ -399,8 +408,8 @@ end-of-csh
 			unset PATH
 			/bin/sh << end-of-sh > /dev/null 2>&1
 				. $i
-				list=\`echo \$PATH | /usr/bin/sed -e \
-				    's/^:/.:/;s/:$/:./;s/::/:.:/g;s/:/ /g'\`
+				list=\$(echo \$PATH | /usr/bin/sed -e \
+				    's/^:/.:/;s/:$/:./;s/::/:.:/g;s/:/ /g')
 				/bin/ls -ldgT \$list > $TMP1
 end-of-sh
 			export PATH=$SAVE_PATH
@@ -432,7 +441,7 @@ fi
 # Root and uucp should both be in /etc/ftpusers.
 #
 if checkyesno check_ftpusers; then
-	list="uucp "`awk '$2 == 0 { print $1 }' $MPBYUID`
+	list="uucp "$(awk '$2 == 0 { print $1 }' $MPBYUID)
 	for i in $list; do
 		if /usr/libexec/ftpd -C $i ; then
 			printf "\t$i is not denied\n"
@@ -472,7 +481,7 @@ if checkyesno check_rhosts; then
 	sort -k2 |
 	while read uid homedir; do
 		if [ -f ${homedir}/.rhosts ] ; then
-			rhost=`ls -ldgT ${homedir}/.rhosts`
+			rhost=$(ls -ldgT ${homedir}/.rhosts)
 			printf -- "$uid: $rhost\n"
 		fi
 	done > $OUTPUT
@@ -501,7 +510,7 @@ if checkyesno check_homes; then
 		permit_usergroups=1 || permit_usergroups=0
 	while read uid homedir; do
 		if [ -d ${homedir}/ ] ; then
-			file=`ls -ldgT ${homedir}`
+			file=$(ls -ldgT ${homedir})
 			printf -- "$uid $file\n"
 		fi
 	done < $MPBYPATH |
@@ -524,7 +533,7 @@ if checkyesno check_homes; then
 		for f in $list ; do
 			file=${homedir}/${f}
 			if [ -f $file ] ; then
-				printf -- "$uid $f `ls -ldgT $file`\n"
+				printf -- "$uid $f $(ls -ldgT $file)\n"
 			fi
 		done
 	done < $MPBYPATH |
@@ -553,7 +562,7 @@ if checkyesno check_homes; then
 		for f in $list ; do
 			file=${homedir}/${f}
 			if [ -f $file ] ; then
-				printf -- "$uid $f `ls -ldgT $file`\n"
+				printf -- "$uid $f $(ls -ldgT $file)\n"
 			fi
 		done
 	done < $MPBYPATH |
@@ -840,7 +849,7 @@ if checkyesno check_mtree; then
 
 	for file in /etc/mtree/*.secure; do
 		[ $file = '/etc/mtree/*.secure' ] && continue
-		tree=`sed -n -e '3s/.* //p' -e 3q $file`
+		tree=$(sed -n -e '3s/.* //p' -e 3q $file)
 		mtree $check_mtree_flags -f $file -p $tree > $TMP1
 		if [ -s $TMP1 ]; then
 			printf "\nChecking $tree:\n"
@@ -857,8 +866,8 @@ fi
 #
 if checkyesno check_disklabels; then
 		# migrate old disklabels
-	for file in `ls -1d $backup_dir/$backup_dir/disklabel.* \
-	    $backup_dir/disklabel.* 2>/dev/null`; do
+	for file in $(ls -1d $backup_dir/$backup_dir/disklabel.* \
+	    $backup_dir/disklabel.* 2>/dev/null); do
 		migrate_file "$file" "$work_dir/${file##*/}"
 	done
 
@@ -868,14 +877,14 @@ if checkyesno check_disklabels; then
 	xargs rm < $LABELS
 
 		# generate disklabels of all disks excluding:	cd dk fd md st
-	disks=`iostat -x | awk 'NR > 1 && $1 !~ /^[cfm]d|dk|st|nfs/ { print $1; }'`
+	disks=$(iostat -x | awk 'NR > 1 && $1 !~ /^[cfm]d|dk|st|nfs/ { print $1; }')
 	for i in $disks; do
 		disklabel $i > "$work_dir/disklabel.$i" 2>/dev/null
 	done
 
 		# if fdisk is available, generate fdisks for:	ed ld sd wd
 	if [ -x /sbin/fdisk ]; then
-		disks=`iostat -x| awk 'NR > 1 && $1 ~ /^[elsw]d/ { print $1; }'`
+		disks=$(iostat -x | awk 'NR > 1 && $1 ~ /^[elsw]d/ { print $1; }')
 		for i in $disks; do
 			/sbin/fdisk $i > "$work_dir/fdisk.$i" 2>/dev/null
 		done
@@ -883,7 +892,7 @@ if checkyesno check_disklabels; then
 
 		# if dkctl is available, generate dkctl listwedges for:	ed ld sd wd cgd ofdisk ra rl raid
 	if [ -x /sbin/dkctl ]; then
-		disks=`iostat -x| awk 'NR > 1 && $1 ~ /^[elsw]d|cgd|ofdisk|r[al]|raid/ { print $1; }'`
+		disks=$(iostat -x | awk 'NR > 1 && $1 ~ /^[elsw]d|cgd|ofdisk|r[al]|raid/ { print $1; }')
 		for i in $disks; do
 			/sbin/dkctl $i listwedges > "$work_dir/wedges.$i" 2>/dev/null
 		done
@@ -910,10 +919,12 @@ fi
 
 # Check for changes in the list of installed pkgs
 #
-if checkyesno check_pkgs && [ -d $pkgdb_dir ]; then
+if checkyesno check_pkgs && have_pkgs; then
 	pkgs=$work_dir/pkgs
 	migrate_file "$backup_dir/pkgs" "$pkgs"
-	(	cd $pkgdb_dir
+	pkg_dbdir=$(pkg_admin config-var PKG_DBDIR)
+	: ${pkg_dbdir:=/var/db/pkg}
+	(	cd $pkg_dbdir
 		$pkg_info | sort
 		echo ""
 		find . \( -name +REQUIRED_BY -o -name +CONTENTS \) -print0 |
@@ -990,6 +1001,24 @@ if [ -n "$CHANGELIST" ]; then
 	comm -23 $TMP1 $TMP2 | while read file; do
 		backup_and_diff "$file" yes
 	done
+fi
+
+if have_pkgs; then
+	if checkyesno check_pkg_vulnerabilities; then
+		pkg_admin ${_compat_K_flag} audit >${OUTPUT} 2>&1
+		if [ -s ${OUTPUT} ]; then
+			printf "\nInstalled vulnerable packages:\n"
+			cat ${OUTPUT}
+		fi
+	fi
+
+	if checkyesno check_pkg_signatures; then
+		pkg_admin ${_compat_K_flag} check >${OUTPUT} 2>&1
+		if [ $? -ne 0 ]; then
+			printf "\nFiles with invalid signatures:\n"
+			cat ${OUTPUT}
+		fi
+	fi
 fi
 
 if [ -f /etc/security.local ]; then
diff --git a/usr.sbin/postinstall/postinstall b/usr.sbin/postinstall/postinstall
--- a/usr.sbin/postinstall/postinstall
+++ b/usr.sbin/postinstall/postinstall
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: postinstall,v 1.106 2009/10/13 07:47:00 apb Exp $
+# $NetBSD: postinstall,v 1.129.2.9 2012/08/15 17:36:46 sborrill Exp $
 #
 # Copyright (c) 2002-2008 The NetBSD Foundation, Inc.
 # All rights reserved.
@@ -35,6 +35,10 @@
 #
 
 #
+# XXX BE SURE TO USE ${DEST_DIR} PREFIX BEFORE ALL REAL FILE OPERATIONS XXX
+#
+
+#
 # checks to add:
 #	- sysctl(8) renames (net.inet6.ip6.bindv6only -> net.inet6.ip6.v6only)
 #	- de* -> tlp* migration (/etc/ifconfig.de*, $ifconfig_de*,
@@ -49,10 +53,12 @@
 # This script is executed as part of a cross build.  Allow the build
 # environment to override the locations of some tools.
 : ${AWK:=awk}
-: ${EGREP:=egrep}
-: ${FGREP:=fgrep}
+: ${DB:=db}
 : ${GREP:=grep}
+: ${HOST_SH:=sh}
 : ${MAKE:=make}
+: ${PWD_MKDB:=/usr/sbin/pwd_mkdb}
+: ${STAT:=stat}
 
 #
 #	helper functions
@@ -354,6 +360,29 @@ rcconf_is_set()
 	)
 }
 
+# rcvar_is_enabled var
+#	Check if rcvar is enabled
+#
+rcvar_is_enabled()
+{
+	[ $# -eq 1 ] || err 3 "USAGE: rcvar_is_enabled var"
+	_rcie_var="$1"
+	(
+		[ -f "${DEST_DIR}/etc/rc.conf" ] && . "${DEST_DIR}/etc/rc.conf"
+		eval _rcie_val="\${${_rcie_var}}"
+		case $_rcie_val in
+		#	"yes", "true", "on", or "1"
+		[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
+			exit 0
+			;;
+
+		*)
+			exit 1
+			;;
+		esac
+	)
+}
+
 # find_file_in_dirlist() file message dir1 [...] --
 #	Find which directory file is in, and sets ${dir} to match.
 #	Returns 0 if matched, otherwise 1 (and sets ${dir} to "").
@@ -382,31 +411,6 @@ find_file_in_dirlist()
 	return 1
 }
 
-# stat op format target value
-#	Call stat(1) on the given target according to the given format,
-#	if stat(1) is available (it is presumed to live in /usr/bin).
-#	If it is not available, this routine will always succeed, otherwise
-#	it returns 0 or 1, depending on whether or not the output from
-#	stat(1) matches the expected value.
-#
-stat()
-{
-	_stop="$1"
-	_stfmt="$2"
-	_sttgt="$3"
-	_stval="$4"
-
-	if [ ! -x /usr/bin/stat ]; then
-		msg \
-    "(/usr/bin/stat not available; skipping ${_stop} on ${_sttgt})"
-		return 0
-	fi
-
-	_stres="$(/usr/bin/stat -q -f "${_stfmt}" "${_sttgt}")"
-	[ "${_stres}" = "${_stval}" ]
-	return $?
-}
-
 # file_exists_exact path
 #	Returns true if a file exists in the ${DEST_DIR} whose name
 #	is exactly ${path}, interpreted in a case-sensitive way
@@ -425,7 +429,7 @@ file_exists_exact()
 		_dirname="$(dirname "${_path}" 2>/dev/null)"
 		_basename="$(basename "${_path}" 2>/dev/null)"
 		ls -fa "${DEST_DIR}${_dirname}" 2> /dev/null \
-			| ${FGREP} -x "${_basename}" >/dev/null \
+			| ${GREP} -F -x "${_basename}" >/dev/null \
 			|| return 1
 		_path="${_dirname}"
 	done
@@ -482,6 +486,14 @@ obsolete_libs()
 	[ $# -eq 1 ] || err 3 "USAGE: obsolete_libs dir"
 	dir="$1"
 
+	_obsolete_libs "${dir}"
+	_obsolete_libs "/usr/libdata/debug/${dir}"
+}
+
+_obsolete_libs()
+{ 
+	dir="$1"
+
 	(
 
 	if [ ! -e "${DEST_DIR}/${dir}" ]
@@ -522,7 +534,7 @@ function checklib(results, line, regex) {
 	}
 }
 
-/^lib.*\.so\.[0-9]+\.[0-9]+(\.[0-9]+)?$/ {
+/^lib.*\.so\.[0-9]+\.[0-9]+(\.[0-9]+)?(\.debug)?$/ {
 	if (AllLibs)
 		checklib(minor, $0, "^lib.*\\.so\\.")
 	else
@@ -633,7 +645,7 @@ detect_x11()
 			MKX11=no
 			X11ROOTDIR=
 		fi
-		X11SRCDIR=/nonexisent/xsrc
+		X11SRCDIR=/nonexistent/xsrc
 	fi
 }
 
@@ -643,9 +655,10 @@ detect_x11()
 #
 
 #
-#	bluetooth
+#	Bluetooth
 #
-additem bluetooth "bluetooth configuration is up to date"
+
+additem bluetooth "Bluetooth configuration is up to date"
 do_bluetooth()
 {
 	[ -n "$1" ] || err 3 "USAGE: do_bluetooth fix|check"
@@ -660,6 +673,18 @@ do_bluetooth()
 	move_file "${op}" "${DEST_DIR}/var/db/btdev.xml" \
 			"${DEST_DIR}/var/db/btdevctl.plist"
 	failed=$(( ${failed} + $? ))
+
+	notfixed=""
+	if [ "${op}" = "fix" ]; then
+		notfixed="${NOT_FIXED}"
+	fi
+	for _v in btattach btconfig btdevctl; do
+		if rcvar_is_enabled "${_v}"; then
+			msg \
+    "${_v} is obsolete in rc.conf(5)${notfixed}: use bluetooth=YES"
+			failed=$(( ${failed} + 1 ))
+		fi
+	done
 
 	return ${failed}
 }
@@ -703,9 +728,32 @@ do_defaults()
 	op="$1"
 	failed=0
 
+	# Except for i386 and amd64, rc.conf(5) should be the same as the
+	# one obtained from a source directory
+	extra_scripts="rc.conf"
+	if [ "$MACHINE" = "i386" -o "$MACHINE" = "amd64" ]; then
+		if $SOURCEMODE; then
+			extra_scripts=	# clear
+
+			# Generate and compare the correct rc.conf(5) file
+			mkdir "${SCRATCHDIR}/defaults"
+
+			cat "${SRC_DIR}/etc/defaults/rc.conf" \
+			    "${SRC_DIR}/etc/etc.${MACHINE}/rc.conf.append" \
+			    > "${SCRATCHDIR}/defaults/rc.conf"
+
+			compare_dir "${op}" "${SCRATCHDIR}/defaults" \
+			    "${DEST_DIR}/etc/defaults" \
+			    444 \
+			    "rc.conf"
+			failed=$(( ${failed} + $? ))
+		fi
+	fi
+
 	compare_dir "$op" "${SRC_DIR}/etc/defaults" "${DEST_DIR}/etc/defaults" \
 		444 \
-		daily.conf monthly.conf rc.conf security.conf weekly.conf
+		daily.conf monthly.conf security.conf \
+		weekly.conf ${extra_scripts}
 	failed=$(( ${failed} + $? ))
 
 	find_file_in_dirlist pf.boot.conf "pf.boot.conf" \
@@ -775,7 +823,7 @@ do_fontconfig()
 		failed=1
 	fi
 
-	if [ "$op" = "check" -a "$failed" = 1 ]; then
+	if [ "$failed" = 1 ]; then
 		msg \
     "Broken fontconfig configuration found; please delete these files"
 		msg \
@@ -807,7 +855,24 @@ do_gid()
 
 	check_ids "$1" groups "${DEST_DIR}/etc/group" \
 	    named ntpd sshd authpf _pflogd _rwhod _proxy _timedc \
-	    _sdpd _httpd _mdnsd
+	    _sdpd _httpd _mdnsd _tests _tcpdump _tss
+}
+
+#
+#	gpio
+#
+additem gpio "gpio configuration is up to date"
+do_gpio()
+{
+	[ -n "$1" ] || err 3 "USAGE: do_gpio fix|check"
+	op="$1"
+	failed=0
+
+	populate_dir "$op" true "${SRC_DIR}/etc" "${DEST_DIR}/etc" 644 \
+		gpio.conf
+	failed=$(( ${failed} + $? ))
+
+	return ${failed}
 }
 
 #
@@ -933,12 +998,7 @@ do_mtree()
 	if ! $SOURCEMODE; then
 		MTREE_DIR="${SRC_DIR}/etc/mtree"
 	else
-		extrafile=/dev/null
-		if [ "${MKX11}" != "no" ]; then
-			get_makevar X11FLAVOUR
-			extrafile="${SRC_DIR}/etc/mtree/NetBSD.dist.${X11FLAVOUR}"
-		fi
-		cat "${SRC_DIR}/etc/mtree/NetBSD.dist.base" "${extrafile}" > \
+		${MAKE} -C ${SRC_DIR}/etc/mtree emit_dist_file > \
 		    "${SCRATCHDIR}/NetBSD.dist"
 		MTREE_DIR="${SCRATCHDIR}"
 	fi
@@ -1024,6 +1084,43 @@ do_pf()
 }
 
 #
+#	pwd_mkdb
+#
+additem pwd_mkdb "passwd database version"
+do_pwd_mkdb()
+{
+	[ -n "$1" ] || err 3 "USAGE: do_pwd_mkdb  fix|check"
+	op="$1"
+	failed=0
+
+	# XXX Ideally, we should figure out the endianness of the
+	# target machine, and add "-E B"/"-E L" to the db(1) flags,
+	# and "-B"/"-L" to the pwd_mkdb(8) flags if the target is not
+	# the same as the host machine.  It probably doesn't matter,
+	# because we don't expect "postinstall fix pwd_mkdb" to be
+	# invoked during a cross build.
+
+	set -- $(${DB} -q -Sb -Ub -To -N hash ${DEST_DIR}/etc/pwd.db \
+		'VERSION\0')
+	case "$2" in
+	'\001\000\000\000') return 0 ;; # version 1, little-endian
+	'\000\000\000\001') return 0 ;; # version 1, big-endian
+	esac
+
+	if [ "${op}" = "check" ]; then
+		msg "Update format of passwd database"
+		failed=1
+	elif ! ${PWD_MKDB} -V 1 -d ${DEST_DIR:-/} ${DEST_DIR}/etc/master.passwd; then
+		msg "Can't update format of passwd database"
+		failed=1
+	else
+		msg "Updated format of passwd database"
+	fi
+
+	return ${failed}
+}
+
+#
 #	rc
 #
 additem rc "/etc/rc* and /etc/rc.d/ being up to date"
@@ -1050,24 +1147,26 @@ do_rc()
 	compare_dir "${op}" "${SRC_DIR}/etc/rc.d" "${DEST_DIR}/etc/rc.d" 555 \
 		DAEMON DISKS LOGIN NETWORKING SERVERS \
 		accounting altqd amd apmd \
-		bootconf.sh bootparams btattach btconfig btdevctl bthcid \
+		bluetooth bootconf.sh bootparams \
 		ccd cgd cleartmp cron \
 		dhclient dhcpcd dhcpd dhcrelay dmesg downinterfaces envsys \
 		fsck fsck_root ftp_proxy ftpd \
 		gpio \
 		hostapd httpd \
 		identd ifwatchd inetd ipfilter ipfs ipmon ipnat ipsec \
-		irdaattach iscsi_target isdnd \
+		irdaattach iscsi_target isdnd isibootd \
 		kdc \
 		ldconfig local lpd lvm\
-		mdnsd mixerctl mopd motd mountall mountcritlocal \
+		makemandb mdnsd mixerctl mopd motd mountall mountcritlocal \
 		mountcritremote mountd moused mrouted \
-		named ndbootd network newsyslog nfsd nfslocking ntpd ntpdate \
+		named ndbootd network newsyslog nfsd nfslocking npf \
+		ntpd ntpdate \
 		perusertmp pf pf_boot pflogd postfix powerd ppp pwcheck \
 		quota \
-		racoon rpcbind raidframe raidframeparity rarpd rbootd rndctl \
+		racoon rpcbind raidframe raidframeparity random_seed \
+		rarpd rbootd rndctl \
 		root route6d routed rtadvd rtclocaltime rtsold rwho \
-		savecore screenblank sdpd securelevel sshd \
+		savecore screenblank securelevel sshd \
 		staticroute swap1 swap2 sysctl sysdb syslogd \
 		timed tpctl ttys \
 		veriexec virecover wdogctl wpa_supplicant wscons wsmoused \
@@ -1090,7 +1189,8 @@ do_rc()
 	fi
 
 		# check for obsolete rc.d files
-	for f in NETWORK btcontrol btuartd fsck.sh kerberos nfsiod servers \
+	for f in NETWORK btattach btconfig btcontrol btdevctl bthcid btuartd \
+	    fsck.sh kerberos nfsiod sdpd servers \
 	    systemfs daemon gated login poffd portmap sunndd xntpd; do
 		fd="/etc/rc.d/${f}"
 		[ -e "${DEST_DIR}${fd}" ] && echo "${fd}"
@@ -1101,14 +1201,13 @@ do_rc()
 	set --	amd amd_master \
 		btcontrol btcontrol_devices \
 		critical_filesystems critical_filesystems_beforenet \
-		defcorename \
-		ip6forwarding \
 		mountcritlocal mountcritremote \
+		network ip6forwarding \
 		network nfsiod_flags \
 		sdpd sdpd_control \
 		sdpd sdpd_groupname \
 		sdpd sdpd_username \
-		sysctl
+		sysctl defcorename
 	while [ $# -gt 1 ]; do
 		if rcconf_is_set "${op}" "$1" "$2" 1; then
 			failed=1
@@ -1138,9 +1237,11 @@ do_sendmail()
 	for f in /etc/mail/helpfile /etc/mail/local-host-names \
 	    /etc/mail/sendmail.cf /etc/mail/submit.cf /etc/rc.d/sendmail \
 	    /etc/rc.d/smmsp /usr/share/misc/sendmail.hf \
-	    $(find /usr/share/sendmail -type f) \
-	    $(find /usr/share/sendmail -type d) /var/log/sendmail.st \
-	    /var/spool/clientmqueue /var/spool/mqueue; do
+	    $(find ${DEST_DIR}/usr/share/sendmail -type f) \
+	    $(find ${DEST_DIR}/usr/share/sendmail -type d) \
+	    ${DEST_DIR}/var/log/sendmail.st \
+	    ${DEST_DIR}/var/spool/clientmqueue \
+	    ${DEST_DIR}/var/spool/mqueue; do
 		[ -e "${DEST_DIR}${f}" ] && echo "${f}"
 	done | obsolete_paths "${op}"
 	failed=$(( ${failed} + $? ))
@@ -1158,7 +1259,7 @@ do_mailerconf()
 	op="$1"
 
 	failed=0
-	mta_path="$(${AWK} '/^sendmail[ \t]/{print$2}' /etc/mailer.conf)"
+	mta_path="$(${AWK} '/^sendmail[ \t]/{print$2}' ${DEST_DIR}/etc/mailer.conf)"
 	old_sendmail_path="/usr/libexec/sendmail/sendmail"
 	if [ "${mta_path}" = "${old_sendmail_path}" ]; then
 	    if [ "$op" = check ]; then
@@ -1310,10 +1411,13 @@ do_x11()
 		msg "${_etcx11} is not a directory; skipping check"
 		return 0
 	fi
-	_libx11="${DEST_DIR}/usr/X11R6/lib/X11"
-	if [ ! -d "${_libx11}" ]; then
-		msg "${_libx11} is not a directory; skipping check"
-		return 0
+	if [ -d "${DEST_DIR}/usr/X11R6/." ]
+	then
+		_libx11="${DEST_DIR}/usr/X11R6/lib/X11"
+		if [ ! -d "${_libx11}" ]; then
+			msg "${_libx11} is not a directory; skipping check"
+			return 0
+		fi
 	fi
 
 	_notfixed=""
@@ -1386,7 +1490,7 @@ ${pcpath} was a directory, should be a file.
 	# then it will not be deleted.
 	( [ -f "${DEST_DIR}"/var/db/obsolete/xbase ] \
 	    &&  sort -ru "${DEST_DIR}"/var/db/obsolete/xbase \
-	    | ${EGREP} "^\\.?${pcpath}/" ;
+	    | ${GREP} -E "^\\.?${pcpath}/" ;
 	    echo "${pcpath}" ) \
 	| obsolete_paths "${op}"
 	failed=$(( ${failed} + $? ))
@@ -1424,7 +1528,7 @@ do_uid()
 
 	check_ids "$1" users "${DEST_DIR}/etc/master.passwd" \
 	    named ntpd postfix sshd _pflogd _rwhod _proxy _timedc \
-	    _sdpd _httpd _mdnsd
+	    _sdpd _httpd _mdnsd _tests _tcpdump _tss
 }
 
 
@@ -1439,6 +1543,152 @@ do_varrwho()
 	contents_owner "$1" "${DEST_DIR}/var/rwho" _rwhod _rwhod
 }
 
+
+#
+#	tcpdumpchroot
+#
+additem tcpdumpchroot "remove /var/chroot/tcpdump/etc/protocols"
+do_tcpdumpchroot()
+{
+	[ -n "$1" ] || err 3 "USAGE: do_tcpdumpchroot  fix|check"
+
+	failed=0;
+	if [ -r ${DEST_DIR}/var/chroot/tcpdump/etc/protocols ]; then
+		if [ "$1" = "fix" ]; then
+			rm ${DEST_DIR}/var/chroot/tcpdump/etc/protocols
+			failed=$(( ${failed} + $? ))
+			rmdir  ${DEST_DIR}/var/chroot/tcpdump/etc
+			failed=$(( ${failed} + $? ))
+		else
+			failed=1
+		fi
+	fi
+	return ${failed}
+}
+
+
+#
+#	atf
+#
+additem atf "install missing atf configuration files and validate them"
+do_atf()
+{
+	[ -n "$1" ] || err 3 "USAGE: do_atf  fix|check"
+	op="$1"
+	failed=0
+
+	# Ensure atf configuration files are in place.
+	if find_file_in_dirlist NetBSD.conf "NetBSD.conf" \
+	    "${SRC_DIR}/external/bsd/atf/etc/atf" \
+	    "${SRC_DIR}/etc/atf"; then
+			# ${dir} is set by find_file_in_dirlist()
+		populate_dir "${op}" true "${dir}" "${DEST_DIR}/etc/atf" 644 \
+		    NetBSD.conf common.conf || failed=1
+	else
+		failed=1
+	fi
+	if find_file_in_dirlist atf-run.hooks "atf-run.hooks" \
+	    "${SRC_DIR}/external/bsd/atf/dist/atf-run/sample" \
+	    "${SRC_DIR}/etc/atf"; then
+			# ${dir} is set by find_file_in_dirlist()
+		populate_dir "${op}" true "${dir}" "${DEST_DIR}/etc/atf" 644 \
+		    atf-run.hooks || failed=1
+	else
+		failed=1
+	fi
+
+	# Validate the _atf to _tests user/group renaming.
+	if [ -f "${DEST_DIR}/etc/atf/common.conf" ]; then
+		handle_atf_user "${op}" || failed=1
+	else
+		failed=1
+	fi
+
+	return ${failed}
+}
+
+handle_atf_user()
+{
+	local op="$1"
+	local failed=0
+
+	local conf="${DEST_DIR}/etc/atf/common.conf"
+	if grep '[^#]*unprivileged-user[ \t]*=.*_atf' "${conf}" >/dev/null
+	then
+		if [ "$1" = "fix" ]; then
+			sed -e \
+			    "/[^#]*unprivileged-user[\ t]*=/s/_atf/_tests/" \
+			    "${conf}" >"${conf}.new"
+			failed=$(( ${failed} + $? ))
+			mv "${conf}.new" "${conf}"
+			failed=$(( ${failed} + $? ))
+			msg "Set unprivileged-user=_tests in ${conf}"
+		else
+			msg "unprivileged-user=_atf in ${conf} should be" \
+			    "unprivileged-user=_tests"
+			failed=1
+		fi
+	fi
+
+	return ${failed}
+}
+
+#
+#	catpages
+#
+obsolete_catpages()
+{
+	basedir="$2"
+	section="$3"
+	mandir="${basedir}/man${section}"
+	catdir="${basedir}/cat${section}"
+	test -d "$mandir" || return 0
+	test -d "$catdir" || return 0
+	(cd "$mandir" && find . -type f) | {
+	failed=0
+	while read manpage; do
+		manpage="${manpage#./}"
+		case "$manpage" in
+		*.Z)
+			catname="$catdir/${manpage%.*.Z}.0"
+			;;
+		*.gz)
+			catname="$catdir/${manpage%.*.gz}.0"
+			;;
+		*)
+			catname="$catdir/${manpage%.*}.0"
+			;;
+		esac
+		test -e "$catname" -a "$catname" -ot "$mandir/$manpage" || continue
+		if [ "$1" = "fix" ]; then
+			rm "$catname"
+			failed=$(( ${failed} + $? ))
+			msg "Removed obsolete cat page $catname"
+		else
+			msg "Obsolete cat page $catname"
+			failed=1
+		fi
+	done
+	exit $failed
+	}
+}
+
+additem catpages "remove outdated cat pages"
+do_catpages()
+{
+	failed=0
+	for manbase in /usr/share/man /usr/X11R6/man /usr/X11R7/man; do
+		for sec in 1 2 3 4 5 6 7 8 9; do
+			obsolete_catpages $1 ${DEST_DIR}${manbase} ${sec}
+			failed=$(( ${failed} + $? ))
+			if [ "$1" = "fix" ]; then
+				rmdir ${DEST_DIR}${manbase}/cat${sec}/* 2>/dev/null
+				rmdir ${DEST_DIR}${manbase}/cat${sec} 2>/dev/null
+			fi
+		done
+	done
+	return $failed
+}
 
 #
 #	obsolete
@@ -1470,6 +1720,91 @@ do_obsolete()
 
 
 #
+#	ptyfsoldnodes
+#
+additem ptyfsoldnodes "remove legacy device nodes when using ptyfs"
+do_ptyfsoldnodes()
+{
+	[ -n "$1" ] || err 3 "USAGE: do_ptyfsoldnodes  fix|check"
+	_ptyfs_op="$1"
+
+	# Check whether ptyfs is in use
+	failed=0;
+	if ! ${GREP} -E "^ptyfs" "${DEST_DIR}/etc/fstab" > /dev/null; then
+		msg "ptyfs is not in use"
+		return 0
+	fi
+
+	# Find the device major numbers for the pty master and slave
+	# devices, by parsing the output from "MAKEDEV -s pty0".
+	#
+	# Output from MAKEDEV looks like this:
+	# ./ttyp0 type=char device=netbsd,5,0 mode=666 gid=0 uid=0
+	# ./ptyp0 type=char device=netbsd,6,0 mode=666 gid=0 uid=0
+	#
+	# Output from awk, used in the eval statement, looks like this:
+	# maj_ptym=6; maj_ptys=5;
+	#
+	eval "$(
+	    ${HOST_SH} "${DEST_DIR}/dev/MAKEDEV" -s pty0 2>/dev/null \
+	    | ${AWK} '\
+	    BEGIN { before_re = ".*device=[a-zA-Z]*,"; after_re = ",.*"; }
+	    /ptyp0/ { maj_ptym = gensub(before_re, "", 1, $0);
+		      maj_ptym = gensub(after_re, "", 1, maj_ptym); }
+	    /ttyp0/ { maj_ptys = gensub(before_re, "", 1, $0);
+		      maj_ptys = gensub(after_re, "", 1, maj_ptys); }
+	    END { print "maj_ptym=" maj_ptym "; maj_ptys=" maj_ptys ";"; }
+	    '
+	    )"
+	#msg "Major numbers are maj_ptym=${maj_ptym} maj_ptys=${maj_ptys}"
+	if [ -z "$maj_ptym" ] || [ -z "$maj_ptys" ]; then
+		msg "Cannot find device major numbers for pty master and slave"
+		return 1
+	fi
+
+	# look for /dev/[pt]ty[p-zP-T][0-9a-zA-Z], and check that they
+	# have the expected device major numbers.  ttyv* is typically not a
+	# pty device, but we check it anyway.
+	#
+	# The "for d1" loop is intended to avoid overflowing ARG_MAX;
+	# otherwise we could have used a single glob pattern.
+	#
+	# If there are no files that match a particular pattern,
+	# then stat prints something like:
+	#    stat: /dev/[pt]tyx?: lstat: No such file or directory
+	# and we ignore it.  XXX: We also ignore other error messages.
+	#
+	_ptyfs_tmp="$(mktemp /tmp/postinstall.ptyfs.XXXXXXXX)"
+	for d1 in p q r s t u v w x y z P Q R S T; do
+		${STAT} -f "%Hr %N" "${DEST_DIR}/dev/"[pt]ty${d1}? 2>&1
+	done \
+	| while read -r major node ; do
+		case "$major" in
+		${maj_ptym}|${maj_ptys}) echo "$node" ;;
+		esac
+	done >"${_ptyfs_tmp}"
+
+	_desc="legacy device node"
+	while read node; do
+		if [ "${_ptyfs_op}" = "check" ]; then
+			msg "Remove ${_desc} ${node}"
+			failed=1
+		else # "fix"
+			if rm "${node}"; then
+				msg "Removed ${_desc} ${node}"
+			else
+				warn "Failed to remove ${_desc} ${node}"
+				failed=1
+			fi
+		fi
+	done < "${_ptyfs_tmp}"
+	rm "${_ptyfs_tmp}"
+
+	return ${failed}
+}
+
+
+#
 #	end of items
 #	------------
 #
@@ -1489,8 +1824,8 @@ Usage: ${PROGNAME} [-s srcdir] [-d destdir] [-m mach] [-a arch] op [item [...]]
 			of the following:
 			* A directory that contains a NetBSD source tree;
 			* A distribution set file such as "etc.tgz" or
-			  "xetc.tgz", or a colon-separated list of such
-			  files;
+			  "xetc.tgz".  Pass multiple -s options to specify
+                          multiple such files;
 			* A temporary directory in which one or both of
 			  "etc.tgz" and "xetc.tgz" have been extracted.
 							[${SRC_DIR:-/}]
@@ -1535,6 +1870,7 @@ main()
 {
 	TGZLIST=		# quoted list list of tgz files
 	SRC_ARGLIST=		# quoted list of one or more "-s" args
+	SRC_DIR="${SRC_ARG}"	# set default value for early usage()
 	N_SRC_ARGS=0		# number of "-s" args
 	TGZMODE=false		# true if "-s" specifies a tgz file
 	DIRMODE=false		# true if "-s" specified a directory
@@ -1691,7 +2027,7 @@ EOF
 	list)
 		echo "Source directory: ${SRC_DIR:-/}"
 		echo "Target directory: ${DEST_DIR:-/}"
-		if [ "${SRC_DIR}" != "${SRC_ARG}" ]; then
+		if $TGZMODE; then
 			echo " (extracted from: ${SRC_ARG})"
 		fi
 		list
@@ -1711,7 +2047,7 @@ EOF
 		# perform each check/fix
 		#
 		echo "Source directory: ${SRC_DIR:-/}"
-		if [ "${SRC_DIR}" != "${SRC_ARG}" ]; then
+		if $TGZMODE; then
 			echo " (extracted from: ${SRC_ARG})"
 		fi
 		echo "Target directory: ${DEST_DIR:-/}"
