Initialize CVS branch wrstuden-fixsa
The per-file CVS branch roots do not exactly match a reconstructed source-branch commit.

diff --git a/usr.sbin/postinstall/postinstall b/usr.sbin/postinstall/postinstall
--- a/usr.sbin/postinstall/postinstall
+++ b/usr.sbin/postinstall/postinstall
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: postinstall,v 1.31 2006/11/26 12:05:21 peter Exp $
+# $NetBSD: postinstall,v 1.31.2.2 2007/04/16 19:44:50 bouyer Exp $
 #
 # Copyright (c) 2002-2005 The NetBSD Foundation, Inc.
 # All rights reserved.
@@ -777,16 +777,12 @@ do_pf()
 	op=$1
 	failed=0
 
-	find_file_in_dirlist pf.conf "pf.conf" \
-	    ${SRC_DIR}/dist/pf/etc ${DEST_DIR}/etc \
-	    || return 1
-
 	find_file_in_dirlist pf.os "pf.os" \
-	    ${SRC_DIR}/dist/pf/etc ${DEST_DIR}/etc \
+	    ${SRC_DIR}/dist/pf/etc ${SRC_DIR}/etc \
 	    || return 1
 
 	populate_dir ${op} true \
-	    ${SRC_DIR}/dist/pf/etc ${DEST_DIR}/etc 644 \
+	    ${dir} ${DEST_DIR}/etc 644 \
 	    pf.conf pf.os
 	failed=$(( ${failed} + $? ))
 
@@ -1152,12 +1148,17 @@ Usage: ${PROGNAME} [-s srcdir] [-d destdir] [-m mach] [-a arch] op [item [...]]
 	If no items are provided, all checks or fixes are applied.
 
 	Options:
-	-s srcdir	Source directory to compare from.
-			This may be src/etc, an extracted copy of "etc.tgz",
-			or the file etc.tgz.  In the latter case, etc.tgz
-			is extracted into a temporary directory to be used
-			as the source directory.	[${SRC_DIR:-/}]
-	-d destdir	Destination directory to check.	[${DEST_DIR:-/}]
+	-s {srcdir|tgzfile|tempdir}
+			Location of the source files.  This may be any
+			of the following:
+			* A directory that contains a NetBSD source tree;
+			* A distribution set file such as "etc.tgz" or
+			  "xetc.tgz", or a colon-separated list of such
+			  files;
+			* A temporary directory in which one or both of
+			  "etc.tgz" and "xetc.tgz" have been extracted.
+							[${SRC_DIR:-/}]
+	-d destdir	Destination directory to check. [${DEST_DIR:-/}]
 	-m mach		MACHINE.			[${MACHINE}]
 	-a arch		MACHINE_ARCH.			[${MACHINE_ARCH}]
 
@@ -1191,7 +1192,19 @@ main()
 	while getopts s:d:m:a: ch; do
 		case ${ch} in
 		s)
-			SRC_DIR=${OPTARG}
+			if [ -f "${OPTARG%%:*}" ]; then
+				# arg refers to a *.tgz file, or a
+				# colon-separated list.
+				# This may happen twice, for both etc.tgz and
+				# xetc.tgz, so we build up a colon-separated
+				# list in TGZLIST.
+				TGZLIST="${TGZLIST}${TGZLIST:+:}${OPTARG}"
+				SRC_ARG="${TGZLIST}"
+			elif [ -d "${OPTARG}" ]; then
+				SRC_ARG=${OPTARG}
+			else
+				err 1 "Invalid argument for -s option"
+			fi
 			;;
 		d)
 			DEST_DIR=${OPTARG}
@@ -1210,24 +1223,29 @@ main()
 	shift $((${OPTIND} - 1))
 	[ $# -gt 0 ] || usage
 
-	orig_SRC_DIR="${SRC_DIR}"
-
 	#
-	# If '-s etc.tgz', extract etc.tgz to a scratch directory
-	# and invoke the copy of etc/postinstall contained within.
+	# If '-s etc.tgz' or '-s etc.tgz:xetc.tgz', extract tgz files
+	# to a scratch directory.
 	#
-	if [ -f "${SRC_DIR}" ]; then
+	if [ -n "${TGZLIST}" ]; then
 		ETCTGZDIR="${SCRATCHDIR}/etc.tgz"
-		echo "Note: -s ${SRC_DIR} is a file,"
+		echo "Note: -s ${SRC_ARG} is a file,"
 		echo "      temporarily extracting to ${ETCTGZDIR}"
 		if ! mkdir "${ETCTGZDIR}"; then
 			err 1 "Can't create ${ETCTGZDIR}"
 		fi
-		cat "${SRC_DIR}" | (
-			cd "${ETCTGZDIR}" &&
-			tar -zxf -
-		) || err 1 "Can't extract ${SRC_DIR}"
+		oldIFS="${IFS}"
+		IFS=:
+		for tgz in ${TGZLIST}; do
+			cat "${tgz}" | (
+				cd "${ETCTGZDIR}" &&
+				tar -zxf -
+			) || err 1 "Can't extract ${tgz}"
+		done
+		IFS="${oldIFS}"
 		SRC_DIR="${ETCTGZDIR}"
+	else
+		SRC_DIR="${SRC_ARG}"
 	fi
 
 	[ -d "${SRC_DIR}" ]	|| err 1 "${SRC_DIR} is not a directory"
@@ -1280,8 +1298,8 @@ main()
 	list)
 		echo "Source directory: ${SRC_DIR:-/}"
 		echo "Target directory: ${DEST_DIR:-/}"
-		if [ "${SRC_DIR}" != "${orig_SRC_DIR}" ]; then
-			echo " (extracted from: ${orig_SRC_DIR})"
+		if [ "${SRC_DIR}" != "${SRC_ARG}" ]; then
+			echo " (extracted from: ${SRC_ARG})"
 		fi
 		list
 		;;
@@ -1300,8 +1318,8 @@ main()
 		# perform each check/fix
 		#
 		echo "Source directory: ${SRC_DIR:-/}"
-		if [ "${SRC_DIR}" != "${orig_SRC_DIR}" ]; then
-			echo " (extracted from: ${orig_SRC_DIR})"
+		if [ "${SRC_DIR}" != "${SRC_ARG}" ]; then
+			echo " (extracted from: ${SRC_ARG})"
 		fi
 		echo "Target directory: ${DEST_DIR:-/}"
 		items_passed=
@@ -1328,7 +1346,7 @@ main()
 			[ "$MACHINE" = "$(uname -m)" ] && m= || m=" -m $MACHINE"
 			cat <<_Fix_me_
 To fix, run:
-    ${0} -s ${orig_SRC_DIR} -d ${DEST_DIR:-/}$m fix${items_failed}
+    ${0} -s ${SRC_ARG} -d ${DEST_DIR:-/}$m fix${items_failed}
 _Fix_me_
 		fi
 
@@ -1345,7 +1363,7 @@ _Fix_me_
 # defaults
 #
 PROGNAME=${0##*/}
-SRC_DIR="/usr/src"
+SRC_ARG="/usr/src"
 DEST_DIR="/"
 : ${MACHINE:=$( uname -m )}	# assume native build if $MACHINE is not set
 : ${MACHINE_ARCH:=$( uname -p )}# assume native build if not set
