Initialize CVS branch netbsd-7-nhusb
The per-file CVS branch roots do not exactly match a reconstructed source-branch commit.

diff --git a/external/bsd/openresolv/dist/resolvconf.in b/external/bsd/openresolv/dist/resolvconf.in
--- a/external/bsd/openresolv/dist/resolvconf.in
+++ b/external/bsd/openresolv/dist/resolvconf.in
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Copyright (c) 2007-2016 Roy Marples
+# Copyright (c) 2007-2014 Roy Marples
 # All rights reserved
 
 # Redistribution and use in source and binary forms, with or without
@@ -25,12 +25,9 @@
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 RESOLVCONF="$0"
-OPENRESOLV_VERSION="3.8.0"
 SYSCONFDIR=@SYSCONFDIR@
 LIBEXECDIR=@LIBEXECDIR@
 VARDIR=@VARDIR@
-RCDIR=@RCDIR@
-RESTARTCMD=@RESTARTCMD@
 
 # Disregard dhcpcd setting
 unset interface_order state_dir
@@ -53,12 +50,11 @@ elif [ -d "$SYSCONFDIR/resolvconf" ]; then
 		interface_order="$(cat "$SYSCONFDIR"/interface-order)"
 	fi
 fi
+TMPDIR="$VARDIR/tmp"
 IFACEDIR="$VARDIR/interfaces"
 METRICDIR="$VARDIR/metrics"
 PRIVATEDIR="$VARDIR/private"
-EXCLUSIVEDIR="$VARDIR/exclusive"
 LOCKDIR="$VARDIR/lock"
-_PWD="$PWD"
 
 warn()
 {
@@ -74,59 +70,52 @@ error_exit()
 usage()
 {
 	cat <<-EOF
-	Usage: ${RESOLVCONF##*/} [options] command [argument]
+	Usage: ${RESOLVCONF##*/} [options]
 
 	Inform the system about any DNS updates.
 
-	Commands:
+	Options:
 	  -a \$INTERFACE    Add DNS information to the specified interface
 	                   (DNS supplied via stdin in resolv.conf format)
+	  -m metric        Give the added DNS information a metric
+	  -p               Mark the interface as private
 	  -d \$INTERFACE    Delete DNS information from the specified interface
-	  -h               Show this help cruft
+	  -f               Ignore non existant interfaces
+	  -I               Init the state dir
+	  -u               Run updates from our current DNS information
+	  -l [\$PATTERN]    Show DNS information, optionally from interfaces
+	                   that match the specified pattern
 	  -i [\$PATTERN]    Show interfaces that have supplied DNS information
                    optionally from interfaces that match the specified
                    pattern
-	  -l [\$PATTERN]    Show DNS information, optionally from interfaces
-	                   that match the specified pattern
-
-	  -u               Run updates from our current DNS information
-
-	Options:
-	  -f               Ignore non existant interfaces
-	  -m metric        Give the added DNS information a metric
-	  -p               Mark the interface as private
-	  -x               Mark the interface as exclusive
-
-	Subscriber and System Init Commands:
-	  -I               Init the state dir
-	  -r \$SERVICE      Restart the system service
-	                   (restarting a non-existent or non-running service
-	                    should have no output and return 0)
-	  -R               Show the system service restart command
 	  -v [\$PATTERN]    echo NEWDOMAIN, NEWSEARCH and NEWNS variables to
 	  		   the console
-	  -V [\$PATTERN]    Same as -v, but only uses configuration in
-	                   $SYSCONFDIR/resolvconf.conf
+	  -h               Show this help cruft
 	EOF
 	[ -z "$1" ] && exit 0
 	echo
 	error_exit "$*"
 }
 
-# Strip any trailing dot from each name as a FQDN does not belong
-# in resolv.conf(5)
-# If you think otherwise, capture a DNS trace and you'll see libc
-# will strip it regardless.
-# This also solves setting up duplicate zones in our subscribers.
-strip_trailing_dots()
+echo_resolv()
 {
-	local n= d=
+	local line= OIFS="$IFS"
 
-	for n; do
-		printf "$d%s" "${n%.}"
-		d=" "
-	done
-	printf "\n"
+	[ -n "$1" -a -e "$IFACEDIR/$1" ] || return 1
+	echo "# resolv.conf from $1"
+	# Our variable maker works of the fact each resolv.conf per interface
+	# is separated by blank lines.
+	# So we remove them when echoing them.
+	while read -r line; do
+		IFS="$OIFS"
+		if [ -n "$line" ]; then
+			# We need to set IFS here to preserve any whitespace
+			IFS=''
+			printf "%s\n" "$line"
+		fi
+	done < "$IFACEDIR/$1"
+	echo
+	IFS="$OIFS"
 }
 
 # Parse resolv.conf's and make variables
@@ -172,14 +161,14 @@ parse_resolv()
 			$islocal || ns="$ns${line#* } "
 			;;
 		"domain "*)
-			search="$(strip_trailing_dots ${line#* })"
 			if [ -z "$domain" ]; then
-				domain="$search"
+				domain="${line#* }"
 				echo "DOMAIN=\"$domain\""
 			fi
+			search="${line#* }"
 			;;
 		"search "*)
-			search="$(strip_trailing_dots ${line#* })"
+			search="${line#* }"
 			;;
 		*)
 			[ -n "$line" ] && continue
@@ -254,152 +243,32 @@ config_mkdirs()
 	return $e
 }
 
-# With the advent of alternative init systems, it's possible to have
-# more than one installed. So we need to try and guess what one we're
-# using unless overriden by configure.
-# Note that restarting a service is a last resort - the subscribers
-# should make a reasonable attempt to reconfigre the service via some
-# method, normally SIGHUP.
-detect_init()
-{
-	[ -n "$RESTARTCMD" ] && return 0
-
-	# Detect the running init system.
-	# As systemd and OpenRC can be installed on top of legacy init
-	# systems we try to detect them first.
-	local status="@STATUSARG@"
-	: ${status:=status}
-	if [ -x /bin/systemctl -a -S /run/systemd/private ]; then
-		RESTARTCMD="if /bin/systemctl --quiet is-active; then
-	/bin/systemctl restart \$1.service;
-fi"
-	elif [ -x /usr/bin/systemctl -a -S /run/systemd/private ]; then
-		RESTARTCMD="if /usr/bin/systemctl --quiet is-active; then
-	/usr/bin/systemctl restart \$1.service;
-fi"
-	elif [ -x /sbin/rc-service -a \
-	    -s /libexec/rc/init.d/softlevel -o -s /run/openrc/softlevel ]
-	then
-		RESTARTCMD="/sbin/rc-service -i \$1 -- -Ds restart"
-	elif [ -x /usr/sbin/invoke-rc.d ]; then
-		RCDIR=/etc/init.d
-		RESTARTCMD="if /usr/sbin/invoke-rc.d --quiet \$1 status 1>/dev/null 2>&1; then
-	/usr/sbin/invoke-rc.d \$1 restart;
-fi"
-	elif [ -x /sbin/service ]; then
-		# Old RedHat
-		RCDIR=/etc/init.d
-		RESTARTCMD="if /sbin/service \$1; then
-	/sbin/service \$1 restart;
-fi"
-	elif [ -x /usr/sbin/service ]; then
-		# Could be FreeBSD
-		RESTARTCMD="if /usr/sbin/service \$1 $status 1>/dev/null 2>&1; then
-	/usr/sbin/service \$1 restart;
-fi"
-	elif [ -x /bin/sv ]; then
-		RESTARTCMD="/bin/sv try-restart \$1"
-	elif [ -x /usr/bin/sv ]; then
-		RESTARTCMD="/usr/bin/sv try-restart \$1"
-	elif [ -e /etc/arch-release -a -d /etc/rc.d ]; then
-		RCDIR=/etc/rc.d
-		RESTARTCMD="if [ -e /var/run/daemons/\$1 ]; then
-	/etc/rc.d/\$1 restart;
-fi"
-	elif [ -e /etc/slackware-version -a -d /etc/rc.d ]; then
-		RESTARTCMD="if /etc/rc.d/rc.\$1 status 1>/dev/null 2>&1; then
-	/etc/rc.d/rc.\$1 restart;
-fi"
-	elif [ -e /etc/rc.d/rc.subr -a -d /etc/rc.d ]; then
-		# OpenBSD
-		RESTARTCMD="if /etc/rc.d/\$1 check 1>/dev/null 2>&1; then
-	/etc/rc.d/\$1 restart;
-fi"
-	else
-		for x in /etc/init.d/rc.d /etc/rc.d /etc/init.d; do
-			[ -d $x ] || continue
-			RESTARTCMD="if $x/\$1 $status 1>/dev/null 2>&1; then
-	$x/\$1 restart;
-fi"
-			break
-		done
-	fi
-
-	if [ -z "$RESTARTCMD" ]; then
-		if [ "$NOINIT_WARNED" != true ]; then
-			warn "could not detect a useable init system"
-			_NOINIT_WARNED=true
-		fi
-		return 1
-	fi
-	_NOINIT_WARNED=
-	return 0
-}
-
-echo_resolv()
-{
-	local line= OIFS="$IFS"
-
-	[ -n "$1" -a -f "$IFACEDIR/$1" ] || return 1
-	echo "# resolv.conf from $1"
-	# Our variable maker works of the fact each resolv.conf per interface
-	# is separated by blank lines.
-	# So we remove them when echoing them.
-	while read -r line; do
-		IFS="$OIFS"
-		if [ -n "$line" ]; then
-			# We need to set IFS here to preserve any whitespace
-			IFS=''
-			printf "%s\n" "$line"
-		fi
-	done < "$IFACEDIR/$1"
-	IFS="$OIFS"
-}
-
 list_resolv()
 {
 	[ -d "$IFACEDIR" ] || return 0
 
-	local report=false list= retval=0 cmd="$1" excl=
+	local report=false list= retval=0 cmd="$1"
 	shift
-
-	case "$IF_EXCLUSIVE" in
-	[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
-		if [ -d "$EXCLUSIVEDIR" ]; then
-			cd "$EXCLUSIVEDIR"
-			for i in *; do
-				if [ -f "$i" ]; then
-					list="${i#* }"
-					break
-				fi
-			done
-		fi
-		excl=true
-		;;
-	*)
-		excl=false
-		;;
-	esac
 
 	# If we have an interface ordering list, then use that.
 	# It works by just using pathname expansion in the interface directory.
 	if [ -n "$1" ]; then
 		list="$*"
 		$force || report=true
-	elif ! $excl; then
+	else
 		cd "$IFACEDIR"
 		for i in $interface_order; do
-			[ -f "$i" ] && list="$list $i"
-			for ii in "$i":* "$i".*; do
-				[ -f "$ii" ] && list="$list $ii"
+			[ -e "$i" ] && list="$list $i"
+			for ii in "$i":*; do
+				[ -e "$ii" ] && list="$list $ii"
 			done
 		done
 		for i in $dynamic_order; do
 			if [ -e "$i" -a ! -e "$METRICDIR/"*" $i" ]; then
 				list="$list $i"
 			fi
-			for ii in "$i":* "$i".*; do
-				if [ -f "$ii" -a ! -e "$METRICDIR/"*" $ii" ]; then
+			for ii in "$i":*; do
+				if [ -e "$ii" -a ! -e "$METRICDIR/"*" $ii" ]; then
 					list="$list $ii"
 				fi
 			done
@@ -407,21 +276,19 @@ list_resolv()
 		if [ -d "$METRICDIR" ]; then
 			cd "$METRICDIR"
 			for i in *; do
-				[ -f "$i" ] && list="$list ${i#* }"
+				list="$list ${i#* }"
 			done
 		fi
 		list="$list *"
 	fi
 
 	cd "$IFACEDIR"
-	retval=1
-	excl=true
 	for i in $(uniqify $list); do
 		# Only list interfaces which we really have
-		if ! [ -f "$i" ]; then
+		if ! [ -e "$i" ]; then
 			if $report; then
 				echo "No resolv.conf for interface $i" >&2
-				retval=2
+				retval=$(($retval + 1))
 			fi
 			continue
 		fi
@@ -430,9 +297,7 @@ list_resolv()
 			printf %s "$i "
 		else
 			echo_resolv "$i"
-			echo
 		fi
-		[ $? = 0 -a "$retval" = 1 ] && retval=0
 	done
 	[ "$cmd" = i -o "$cmd" = "-i" ] && echo
 	return $retval
@@ -540,13 +405,11 @@ make_vars()
 	SEARCH=
 	NAMESERVERS=
 	LOCALNAMESERVERS=
-	
+
 	if [ -n "$name_servers" -o -n "$search_domains" ]; then
 		eval "$(echo_prepend | parse_resolv)"
 	fi
 	if [ -z "$VFLAG" ]; then
-		IF_EXCLUSIVE=1
-		list_resolv -i "$@" >/dev/null || IF_EXCLUSIVE=0
 		eval "$(list_resolv -l "$@" | replace | parse_resolv)"
 	fi
 	if [ -n "$name_servers_append" -o -n "$search_domains_append" ]; then
@@ -596,7 +459,7 @@ make_vars()
 
 force=false
 VFLAG=
-while getopts a:Dd:fhIilm:pRruvVx OPT; do
+while getopts a:Dd:fhIilm:puvV OPT; do
 	case "$OPT" in
 	f) force=true;;
 	h) usage;;
@@ -610,7 +473,6 @@ while getopts a:Dd:fhIilm:pRruvVx OPT; do
 			local_nameservers=
 		fi
 		;;
-	x) IF_EXCLUSIVE=1;;
 	'?') ;;
 	*) cmd="$OPT"; iface="$OPTARG";;
 	esac
@@ -635,18 +497,6 @@ fi
 # -l lists our resolv files, optionally for a specific interface
 if [ "$cmd" = l -o "$cmd" = i ]; then
 	list_resolv "$cmd" "$args"
-	exit $?
-fi
-
-# Restart a service or echo the command to restart a service
-if [ "$cmd" = r -o "$cmd" = R ]; then
-	detect_init || exit 1
-	if [ "$cmd" = r ]; then
-		set -- $args
-		eval $RESTARTCMD
-	else
-		echo "$RESTARTCMD"
-	fi
 	exit $?
 fi
 
@@ -712,38 +562,29 @@ if [ ! -d "$IFACEDIR" ]; then
 		${force}
 		exit $?
 	fi
+else
+	# Delete any existing information about the interface
+	if [ "$cmd" = d ]; then
+		cd "$IFACEDIR"
+		changed=false
+		for i in $args; do
+			if [ -e "$i" ]; then
+				changed=true
+			elif ! ${force}; then
+				warn "No resolv.conf for interface $i"
+			fi
+			rm -f "$i" "$METRICDIR/"*" $i" \
+				"$PRIVATEDIR/$i" || exit $?
+		done
+		if ! ${changed}; then
+			# Set the return code based on the forced flag
+			${force}
+			exit $?
+		fi
+	fi
 fi
 
-# An interface was added, changed, deleted or a general update was called.
-# Due to exclusivity we need to ensure that this is an atomic operation.
-# Our subscribers *may* need this as well if the init system is sub par.
-# As such we spinlock at this point as best we can.
-# We don't use flock(1) because it's not widely available and normally resides
-# in /usr which we do our very best to operate without.
-[ -w "$VARDIR" ] || error_exit "Cannot write to $LOCKDIR"
-: ${lock_timeout:=10}
-while true; do
-	if mkdir "$LOCKDIR" 2>/dev/null; then
-		trap 'rm -rf "$LOCKDIR";' EXIT
-		trap 'rm -rf "$LOCKDIR"; exit 1' INT QUIT ABRT SEGV ALRM TERM
-		echo $$ >"$LOCKDIR/pid"
-		break
-	fi
-	pid=$(cat "$LOCKDIR/pid")
-	if ! kill -0 "$pid"; then
-		warn "clearing stale lock pid $pid"
-		rm -rf "$LOCKDIR"
-		continue
-	fi
-	lock_timeout=$(($lock_timeout - 1))
-	if [ "$lock_timeout" -le 0 ]; then
-		error_exit "timed out waiting for lock from pid $pid"
-	fi
-	sleep 1
-done
-
-case "$cmd" in
-a)
+if [ "$cmd" = a ]; then
 	# Read resolv.conf from stdin
 	resolv="$(cat)"
 	changed=false
@@ -760,7 +601,6 @@ a)
 		changed=true
 		changedfile=true
 	fi
-
 	# Set metric and private before creating the interface resolv.conf file
 	# to ensure that it will have the correct flags
 	[ ! -d "$METRICDIR" ] && mkdir "$METRICDIR"
@@ -778,7 +618,6 @@ a)
 	    "$oldmetric" != "$METRICDIR/* $iface" ] &&
 		changed=true
 	[ -n "$newmetric" ] && echo " " >"$newmetric"
-
 	case "$IF_PRIVATE" in
 	[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
 		if [ ! -d "$PRIVATEDIR" ]; then
@@ -795,97 +634,57 @@ a)
 		fi
 		;;
 	esac
-
-	oldexcl=
-	for x in "$EXCLUSIVEDIR/"*" $iface"; do
-		if [ -f "$x" ]; then
-			oldexcl="$x"
-			break
-		fi
-	done
-	case "$IF_EXCLUSIVE" in
-	[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)
-		if [ ! -d "$EXCLUSIVEDIR" ]; then
-			[ -e "$EXCLUSIVEDIR" ] && rm "$EXCLUSIVEDIR"
-			mkdir "$EXCLUSIVEDIR"
-		fi
-		cd "$EXCLUSIVEDIR"
-		for x in *; do
-			[ -f "$x" ] && break
-		done
-		if [ "${x#* }" != "$iface" ]; then
-			if [ "$x" = "${x% *}" ]; then
-				x=10000000
-			else
-				x="${x% *}"
-			fi
-			if [ "$x" = "0000000" ]; then
-				warn "exclusive underflow"
-			else
-				x=$(($x - 1))
-			fi
-			if [ -d "$EXCLUSIVEDIR" ]; then
-				echo " " >"$EXCLUSIVEDIR/$x $iface"
-			fi
-			changed=true
-		fi
-		;;
-	*)
-		if [ -f "$oldexcl" ]; then
-			rm -f "$oldexcl"
-			changed=true
-		fi
-		;;
-	esac
-
 	if $changedfile; then
-		printf "%s\n" "$resolv" >"$IFACEDIR/$iface" || exit $?
-	elif ! $changed; then
-		exit 0
-	fi
-	unset changed changedfile oldmetric newmetric x oldexcl
-	;;
-
-d)
-	# Delete any existing information about the interface
-	cd "$IFACEDIR"
-	changed=false
-	for i in $args; do
-		if [ -e "$i" ]; then
-			changed=true
-		elif ! ${force}; then
-			warn "No resolv.conf for interface $i"
+		# Ensure that creating the file is an atomic operation
+		if [ ! -d "$TMPDIR" ]; then
+			mkdir -m 0755 -p "$TMPDIR" || \
+			    error_exit \
+				"Failed to create needed directory $TMPDIR"
 		fi
-		rm -f "$i" "$METRICDIR/"*" $i" \
-			"$PRIVATEDIR/$i" \
-			"$EXCLUSIVEDIR/"*" $i" || exit $?
-	done
-	if ! ${changed}; then
-		# Set the return code based on the forced flag
-		${force}
-		exit $?
+		TMPFILE="$TMPDIR/$iface.$$"
+		cleanup() { [ -n "$TMPFILE" ] && rm -f "$TMPFILE"; }
+		trap cleanup EXIT
+		echo "$resolv" >"$TMPFILE" || exit $?
+		mv -f "$TMPFILE" "$IFACEDIR/$iface" || exit $?
+		TMPFILE=
 	fi
-	unset changed i
-	;;
-esac
+	$changed || exit 0
+	unset changed oldmetric newmetric
+fi
 
 case "${resolvconf:-YES}" in
 [Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1) ;;
 *) exit 0;;
 esac
 
-# Try and detect a suitable init system for our scripts
-detect_init
-export RESTARTCMD RCDIR _NOINIT_WARNED
+# An interface was added, deleted or changed.
+# These above actions are atomic, however calling our subcribers is not.
+# Even if we do our very best, the action of restarting the subscriber daemon
+# is not guaranteed to be serialised due to our many flavours of OS we support.
+# As such we spinlock at this point as best we can.
+# We don't use flock(1) because it's not widely available and normally resides
+# in /usr which we do our very best to operate without.
+[ -w "$VARDIR" ] || error_exit "Cannot write to $LOCKDIR"
+: ${lock_timeout:=10}
+while true; do
+	if mkdir "$LOCKDIR" 2>/dev/null; then
+		trap 'rm -rf "$LOCKDIR";' EXIT
+		trap 'rm -rf "$LOCKDIR"; exit 1' INT QUIT ABRT SEGV ALRM TERM
+		echo $$ >"$LOCKDIR/pid"
+		break
+	fi
+	lock_timeout=$(($lock_timeout - 1))
+	if [ "$lock_timeout" -le 0 ]; then
+		pid=$(cat "$LOCKDIR/pid")
+		error_exit "timed out waiting for lock from pid $pid"
+	fi
+	sleep 1
+done
 
 eval "$(make_vars)"
 export RESOLVCONF DOMAINS SEARCH NAMESERVERS LOCALNAMESERVERS
 : ${list_resolv:=list_resolv -l}
 retval=0
-
-# Run scripts in the same directory resolvconf is run from
-# in case any scripts accidently dump files in the wrong place.
-cd "$_PWD"
 for script in "$LIBEXECDIR"/*; do
 	if [ -f "$script" ]; then
 		eval script_enabled="\$${script##*/}"
