Initialize CVS branch FSF
The per-file CVS branch roots do not exactly match a reconstructed source-branch commit.

diff --git a/external/gpl3/gcc/dist/contrib/gcc_update b/external/gpl3/gcc/dist/contrib/gcc_update
--- a/external/gpl3/gcc/dist/contrib/gcc_update
+++ b/external/gpl3/gcc/dist/contrib/gcc_update
@@ -1,20 +1,19 @@
 #! /bin/sh
 #
-# Update a local Subversion, Git or Mercurial tree from the GCC
-# repository, with an emphasis on treating generated files correctly, so
-# that autoconf, gperf et al are not required for the ``end'' user.
+# Update a local Subversion tree from the GCC repository, with an emphasis
+# on treating generated files correctly, so that autoconf, gperf et
+# al are not required for the ``end'' user.
 #
-# (C) 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2009, 
-# 2010, 2011, 2012, 2013, 2014, 2015, 2017 Free Software Foundation
-# Originally by Gerald Pfeifer <gerald@pfeifer.com>, August 1998.
+# (C) 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005 Free Software Foundation
+# Originally by Gerald Pfeifer <pfeifer@dbai.tuwien.ac.at>, August 1998.
 #
 # This script is Free Software, and it can be copied, distributed and
 # modified as defined in the GNU General Public License.  A copy of
 # its license can be downloaded from http://www.gnu.org/copyleft/gpl.html
 #
 #
-# By default all command-line options are passed to `svn update` or `hg/git
-# pull` in addition to $UPDATE_OPTIONS (defined below). If the first parameter
+# By default all command-line options are passed to `svn update` in
+# addition to $UPDATE_OPTIONS (defined below). If the first parameter
 # reads --nostdflags, $UPDATE_OPTIONS as well as this parameter itself
 # are omitted.
 #
@@ -39,14 +38,10 @@
 # contrib/gcc_update --list
 
 
-# Default options used when updating (none).
+# SVN command
+GCC_SVN=${GCC_SVN-${SVN-svn}}
+# Default options used when updating via SVN (none).
 UPDATE_OPTIONS=""
-
-# Set the locale to C to make this script work for users with foreign
-# locale like e.g. French UTF-8.
-LANG=C
-LC_ALL=C
-export LANG LC_ALL
 
 ######## Anything below shouldn't be changed by regular users.
 
@@ -79,20 +74,10 @@ gcc/configure: gcc/configure.ac
 gcc/cstamp-h.in: gcc/configure.ac
 gcc/config.in: gcc/cstamp-h.in
 gcc/fixinc/fixincl.x: gcc/fixinc/fixincl.tpl gcc/fixinc/inclhack.def
-gcc/config/aarch64/aarch64-tune.md: gcc/config/aarch64/aarch64-cores.def gcc/config/aarch64/gentune.sh
-gcc/config/arm/arm-tune.md: gcc/config/arm/arm-cpus.in gcc/config/arm/parsecpu.awk
-gcc/config/arm/arm-tables.opt: gcc/config/arm/arm-cpus.in gcc/config/arm/parsecpu.awk
-gcc/config/avr/t-multilib: gcc/config/avr/avr-mcus.def gcc/config/avr/genmultilib.awk
-gcc/config/c6x/c6x-tables.opt: gcc/config/c6x/c6x-isas.def gcc/config/c6x/genopt.sh
-gcc/config/c6x/c6x-sched.md: gcc/config/c6x/c6x-sched.md.in gcc/config/c6x/gensched.sh
-gcc/config/c6x/c6x-mult.md: gcc/config/c6x/c6x-mult.md.in gcc/config/c6x/genmult.sh
-gcc/config/m68k/m68k-tables.opt: gcc/config/m68k/m68k-devices.def gcc/config/m68k/m68k-isas.def gcc/config/m68k/m68k-microarchs.def gcc/config/m68k/genopt.sh
-gcc/config/mips/mips-tables.opt: gcc/config/mips/mips-cpus.def gcc/config/mips/genopt.sh
-gcc/config/rs6000/rs6000-tables.opt: gcc/config/rs6000/rs6000-cpus.def gcc/config/rs6000/genopt.sh
-gcc/config/tilegx/mul-tables.c: gcc/config/tilepro/gen-mul-tables.cc
-gcc/config/tilepro/mul-tables.c: gcc/config/tilepro/gen-mul-tables.cc
+gcc/config/arm/arm-tune.md: gcc/config/arm/arm-cores.def gcc/config/arm/gentune.sh
 # And then, language-specific files
 gcc/cp/cfns.h: gcc/cp/cfns.gperf
+gcc/java/keyword.h: gcc/java/keyword.gperf
 # testsuite
 # Without this, _Pragma3.c can have a false negative.
 gcc/testsuite/gcc.dg/cpp/_Pragma3.c: gcc/testsuite/gcc.dg/cpp/mi1c.h
@@ -122,59 +107,22 @@ libffi/configure: libffi/configure.ac libffi/aclocal.m4
 libffi/fficonfig.h.in: libffi/configure.ac libffi/aclocal.m4
 libgfortran/aclocal.m4: libgfortran/configure.ac libgfortran/acinclude.m4
 libgfortran/Makefile.in: libgfortran/Makefile.am libgfortran/configure.ac libgfortran/aclocal.m4
-libquadmath/configure: libquadmath/configure.ac libquadmath/aclocal.m4
-libquadmath/aclocal.m4: libquadmath/configure.ac libquadmath/acinclude.m4
-libquadmath/Makefile.in: libquadmath/Makefile.am libquadmath/configure.ac libgfortran/aclocal.m4
 libgfortran/configure: libgfortran/configure.ac libgfortran/aclocal.m4
+libjava/aclocal.m4: libjava/configure.ac
+libjava/Makefile.in: libjava/Makefile.am libjava/configure.ac libjava/aclocal.m4
+libjava/configure: libjava/configure.ac libjava/aclocal.m4
+libjava/libltdl/aclocal.m4: libjava/libltdl/configure.ac libjava/libltdl/acinclude.m4
+libjava/libltdl/Makefile.in: libjava/libltdl/Makefile.am libjava/libltdl/configure.ac libjava/libltdl/aclocal.m4
+libjava/libltdl/configure: libjava/libltdl/configure.ac libjava/libltdl/aclocal.m4
+libjava/libltdl/config-h.in: libjava/libltdl/configure.ac libjava/libltdl/aclocal.m4
 libcpp/aclocal.m4: libcpp/configure.ac
 libcpp/Makefile.in: libcpp/configure.ac libcpp/aclocal.m4
 libcpp/configure: libcpp/configure.ac libcpp/aclocal.m4
 libgomp/aclocal.m4: libgomp/configure.ac libgomp/acinclude.m4
-libgomp/Makefile.am: libgomp/plugin/Makefrag.am
 libgomp/Makefile.in: libgomp/Makefile.am libgomp/aclocal.m4
-libgomp/testsuite/Makefile.in: libgomp/testsuite/Makefile.am libgomp/aclocal.m4
-libgomp/configure.ac: libgomp/plugin/configfrag.ac
+libgomp/testsuite/Makefile.in: libgomp/Makefile.am libgomp/aclocal.m4
 libgomp/configure: libgomp/configure.ac libgomp/aclocal.m4
 libgomp/config.h.in: libgomp/configure.ac libgomp/aclocal.m4
-libhsail-rt/aclocal.m4: libhsail-rt/configure.ac
-libhsail-rt/Makefile.in: libhsail-rt/Makefile.am libhsail-rt/aclocal.m4
-libhsail-rt/configure: libhsail-rt/configure.ac libhsail-rt/aclocal.m4
-libhsail-rt/target-config.h.in: libhsail-rt/configure.ac libhsail-rt/aclocal.m4
-libitm/aclocal.m4: libitm/configure.ac libitm/acinclude.m4
-libitm/Makefile.in: libitm/Makefile.am libitm/aclocal.m4
-libitm/testsuite/Makefile.in: libitm/testsuite/Makefile.am libitm/aclocal.m4
-libitm/configure: libitm/configure.ac libitm/aclocal.m4
-libitm/config.h.in: libitm/configure.ac libitm/aclocal.m4
-libatomic/aclocal.m4: libatomic/configure.ac libatomic/acinclude.m4
-libatomic/Makefile.in: libatomic/Makefile.am libatomic/aclocal.m4
-libatomic/testsuite/Makefile.in: libatomic/testsuite/Makefile.am libatomic/aclocal.m4
-libatomic/configure: libatomic/configure.ac libatomic/aclocal.m4
-libatomic/auto-config.h.in: libatomic/configure.ac libatomic/aclocal.m4
-libsanitizer/aclocal.m4: libsanitizer/configure.ac libsanitizer/acinclude.m4
-libsanitizer/Makefile.in: libsanitizer/Makefile.am libsanitizer/aclocal.m4
-libsanitizer/configure: libsanitizer/configure.ac libsanitizer/aclocal.m4
-libsanitizer/asan/Makefile.in: libsanitizer/asan/Makefile.am libsanitizer/aclocal.m4
-libsanitizer/interception/Makefile.in: libsanitizer/interception/Makefile.am libsanitizer/aclocal.m4
-libsanitizer/sanitizer_common/Makefile.in: libsanitizer/sanitizer_common/Makefile.am libsanitizer/aclocal.m4
-libvtv/aclocal.m4: libvtv/configure.ac libvtv/acinclude.m4
-libvtv/Makefile.in: libvtv/Makefile.am libvtv/aclocal.m4
-libvtv/configure: libvtv/configure.ac libvtv/aclocal.m4
-liboffloadmic/aclocal.m4: liboffloadmic/configure.ac
-liboffloadmic/Makefile.in: liboffloadmic/Makefile.am
-liboffloadmic/configure: liboffloadmic/configure.ac
-liboffloadmic/plugin/aclocal.m4: liboffloadmic/plugin/configure.ac
-liboffloadmic/plugin/Makefile.in: liboffloadmic/plugin/Makefile.am
-liboffloadmic/plugin/configure: liboffloadmic/plugin/configure.ac
-libbacktrace/aclocal.m4: libbacktrace/configure.ac
-libbacktrace/Makefile.in: libbacktrace/Makefile.am libbacktrace/aclocal.m4
-libbacktrace/configure: libbacktrace/configure.ac libbacktrace/aclocal.m4
-libbacktrace/config.h.in: libbacktrace/configure.ac libbacktrace/aclocal.m4
-libphobos/Makefile.in: libphobos/Makefile.am libphobos/configure.ac libphobos/aclocal.m4
-libphobos/aclocal.m4: libphobos/configure.ac libphobos/acinclude.m4
-libphobos/config.h.in: libphobos/configure.ac libphobos/aclocal.m4
-libphobos/configure: libphobos/configure.ac libphobos/aclocal.m4
-libphobos/src/Makefile.in: libphobos/src/Makefile.am libphobos/aclocal.m4
-libphobos/testsuite/Makefile.in: libphobos/testsuite/Makefile.am libphobos/aclocal.m4
 # Top level
 Makefile.in: Makefile.tpl Makefile.def
 configure: configure.ac config/acx.m4
@@ -291,18 +239,9 @@ p
 
 esac
 
-# Check for known version control systems.
-if [ -d .git ] || [ -f .git ]; then
-    GCC_GIT=${GCC_GIT-${GIT-git}}
-    vcs_type="git"
-elif [ -d .hg ]; then
-    GCC_HG=${GCC_HG-${HG-hg}}
-    vcs_type="hg"
-elif [ -d .svn ]; then
-    GCC_SVN=${GCC_SVN-${SVN-svn}}
-    vcs_type="svn"
-else
-    echo "This does not seem to be a GCC GIT/HG/SVN tree!"
+# Check whether this indeed looks like a local SVN tree.
+if [ ! -d .svn ]; then
+    echo "This does not seem to be a GCC SVN tree!"
     exit
 fi
 
@@ -313,106 +252,29 @@ else
     set -- $UPDATE_OPTIONS ${1+"$@"}
 fi
 
-case $vcs_type in
-    git)
-	chat "Updating GIT tree"
+chat "Updating SVN tree"
 
-	$GCC_GIT diff --quiet --exit-code HEAD
-	if [ $? -ne 0 ]; then
-            echo "Attempting to update a dirty git tree!" >&2
-            echo "Commit or stash your changes first and retry." >&2
-            exit 1
-	fi
-
-	$GCC_GIT pull ${silent+-q} --rebase ${1+"$@"}
-	if [ $? -ne 0 ]; then
-            (touch_files_reexec)
-            echo "git pull of full tree failed." >&2
-            exit 1
-	fi
-
-	revision=`$GCC_GIT log -n1 --pretty=%p:%t:%H`
-	branch=`$GCC_GIT name-rev --name-only HEAD || :`
-	;;    
-
-    hg)
-	chat "Updating HG tree"
-
-	# Add -q so untracked files aren't listed.
-	if [ `$GCC_HG status -q | wc -l` -gt 0 ]; then
-            echo "Attempting to update a dirty hg tree!" >&2
-            echo "Commit or revert your changes first and retry." >&2
-            exit 1
-	fi
-
-	# Check for mq extension.  mq patches must be popped so tip has
-	# been converted from the SVN tree.
-	if [ -d .hg/patches ] && [ `$GCC_HG qapplied | wc -l` -gt 0 ]; then
-	    # FIXME: Perhaps pop queue instead?  We could do that since we
-	    # know the tree is clean.
-	    echo "Attempting to update hg tree with mq patches applied!" >&2
-	    echo "Pop your patches first and retry." >&2
-	    exit 1
-	fi
-
-	# Update tree, but make sure to only pull the default branch.
-	# Otherwise all branches in the upstream repo are added, even if
-	# only a single one has been cloned.
-	$GCC_HG pull ${silent+-q} -r`$GCC_HG branch` ${1+"$@"}
-	if [ $? -ne 0 ]; then
-            (touch_files_reexec)
-            echo "hg pull of full tree failed." >&2
-            exit 1
-	fi
-
-	# Update tree.  Needs to be done separately from pull so
-	# gcc_update -rREV works.
-	$GCC_HG update ${silent+-q} ${1+"$@"}
-	if [ $? -ne 0 ]; then
-            (touch_files_reexec)
-            echo "hg update of full tree failed." >&2
-            exit 1
-	fi
-
-	# Extract SVN revision corresponding to parents, as stored by
-	# hg convert.  Before hg 1.4.3, there's no template keyword
-	# corresponding to the extra: tag, so need to use hg log --debug
-	# to extract the info.
-	parents=`$GCC_HG parents --template '{rev}'`
-	convert_revision=`$GCC_HG log --debug -r$parents | \
-	    sed -ne "/^extra:.*convert_revision=svn:/ {
-	        s%^[^/]*/%%
-		p
-	    }"`
-	revision=`echo $convert_revision | sed -e 's/.*@//'`
-	branch=`echo $convert_revision | sed -e 's%branches/%%' -e 's/@.*//'`
-	;;
-
-    svn)
-	chat "Updating SVN tree"
-
-	$GCC_SVN ${silent+-q}  --non-interactive update ${1+"$@"}
-	if [ $? -ne 0 ]; then
-	    (touch_files_reexec)
-	    echo "SVN update of full tree failed." >&2
-	    exit 1
-	fi
-
-	revision=`$GCC_SVN info | awk '/Revision:/ { print $2 }'`
-	branch=`$GCC_SVN info | sed -ne "/^URL:/ {
-	    s,.*/trunk,trunk,
-	    s,.*/branches/,,
-	    s,.*/tags/,,
-	    p
-	}"`
-	;;
-esac
+$GCC_SVN ${silent+-q}  --non-interactive update ${1+"$@"}
+if [ $? -ne 0 ]; then
+    (touch_files_reexec)
+    echo "SVN update of full tree failed." >&2
+    exit 1
+fi
 
 rm -f LAST_UPDATED gcc/REVISION
+
+revision=`svn info | awk '/Revision:/ { print $2 }'`
+branch=`svn info | sed -ne "/URL:/ {
+s,.*/trunk,trunk,
+s,.*/branches/,,
+s,.*/tags/,,
+p
+}"`
 {
-    date
-    echo "`TZ=UTC date` (revision $revision)"
+  date
+  echo "`TZ=UTC date` (revision $revision)"
 } > LAST_UPDATED
+
 echo "[$branch revision $revision]" > gcc/REVISION
 
 touch_files_reexec
diff --git a/external/gpl3/gdb/dist/gdb/gcore b/external/gpl3/gdb/dist/gdb/gcore
--- a/external/gpl3/gdb/dist/gdb/gcore
+++ b/external/gpl3/gdb/dist/gdb/gcore
@@ -1,6 +1,6 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
-#   Copyright (C) 2003-2019 Free Software Foundation, Inc.
+#   Copyright (C) 2003-2014 Free Software Foundation, Inc.
 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -20,39 +20,27 @@
 # It starts up gdb, attaches to the given PID and invokes the gcore command.
 #
 
-# Need to check for -o option, but set default basename to "core".
-prefix=core
-
-# When the -a option is present, this may hold additional commands
-# to ensure gdb dumps all mappings (OS dependent).
-dump_all_cmds=()
-
-while getopts :ao: opt; do
-    case "$opt" in
-        a)
-            case "$OSTYPE" in
-                linux*)
-                    dump_all_cmds=("-ex" "set use-coredump-filter off")
-                    dump_all_cmds+=("-ex" "set dump-excluded-mappings on")
-                    ;;
-            esac
-            ;;
-        o)
-            prefix=$OPTARG
-            ;;
-        *)
-            echo "usage:  i386-pc-linux-gnu-gcore [-a] [-o prefix] pid1 [pid2...pidN]"
-            exit 2
-            ;;
-    esac
-done
-
-shift $((OPTIND-1))
-
 if [ "$#" -eq "0" ]
 then
-    echo "usage:  i386-pc-linux-gnu-gcore [-a] [-o prefix] pid1 [pid2...pidN]"
+    echo "usage:  gcore [-o filename] pid"
     exit 2
+fi
+
+# Need to check for -o option, but set default basename to "core".
+name=core
+
+if [ "$1" = "-o" ]
+then
+    if [ "$#" -lt "3" ]
+    then
+	# Not enough arguments.
+	echo "usage:  gcore [-o filename] pid"
+	exit 2
+    fi
+    name=$2
+
+    # Shift over to start of pid list
+    shift; shift
 fi
 
 # Attempt to fetch the absolute path to the gcore script that was
@@ -84,8 +72,8 @@ fi
 
 # Check if the GDB binary is in the expected path.  If not, just
 # quit with a message.
-if [ ! -f "$binary_path/i386-pc-linux-gnu-gdb" ]; then
-  echo "gcore: GDB binary (${binary_path}/i386-pc-linux-gnu-gdb) not found"
+if [ ! -f "$binary_path"/gdb ]; then
+  echo "gcore: GDB binary (${binary_path}/gdb) not found"
   exit 1
 fi
 
@@ -93,20 +81,18 @@ fi
 rc=0
 
 # Loop through pids
-for pid in "$@"
+for pid in $*
 do
 	# `</dev/null' to avoid touching interactive terminal if it is
 	# available but not accessible as GDB would get stopped on SIGTTIN.
-	"$binary_path/i386-pc-linux-gnu-gdb" </dev/null \
-	    --nx --batch --readnever \
+	$binary_path/gdb </dev/null --nx --batch \
 	    -ex "set pagination off" -ex "set height 0" -ex "set width 0" \
-	    "${dump_all_cmds[@]}" \
-	    -ex "attach $pid" -ex "gcore $prefix.$pid" -ex detach -ex quit
+	    -ex "attach $pid" -ex "gcore $name.$pid" -ex detach -ex quit
 
-	if [ -r "$prefix.$pid" ] ; then
+	if [ -r $name.$pid ] ; then 
 	    rc=0
 	else
-	    echo "i386-pc-linux-gnu-gcore: failed to create $prefix.$pid"
+	    echo "gcore: failed to create $name.$pid"
 	    rc=1
 	    break
 	fi
